###############################-Imports-###############################
import webbrowser
from PyQt5.QtWidgets import *
from PyQt5 import QtCore as QtCore
from PyQt5.QtCore import Qt as Qt
from PyQt5.QtGui import *
import getpass
import time
import os



###############################-Global Variables-###############################

#Hooray for insanely long strings


allCards = '''
   "id": 10,
   "name": "Catacomb Curator",
   "mana": 1,
   "id": 87037,
   "name": "Barbed Portcullis",
   "mana": 3,
   "id": 87051,
   "name": "Best Friends",
   "mana": 1,
   "id": 188,
   "name": "Rockdrake Egg",
   "mana": 2,
   "id": 279,
   "name": "Seraph",
   "mana": 5,
   "id": 356,
   "name": "Jungle Shepherd",
   "mana": 3,
   "id": 87061,
   "name": "Rebuild Differently",
   "mana": 7,
   "id": 5,
   "name": "Half Life",
   "mana": 3,
   "id": 303,
   "name": "Whetstone",
   "mana": 1,
   "id": 338,
   "name": "Fill the Coffers",
   "mana": 6,
   "id": 364,
   "name": "Magic, Unburdened",
   "mana": 8,
   "id": 100058,
   "name": "Glamoured Gladius",
   "mana": 2,
   "id": 1016,
   "name": "Inferno",
   "mana": 7,
   "id": 1171,
   "name": "Double Dealer",
   "mana": 7,
   "id": 9,
   "name": "Nether Nanny",
   "mana": 4,
   "id": 69,
   "name": "Malfunctioning Servitor",
   "mana": 3,
   "id": 1018,
   "name": "Black Jaguar",
   "mana": 2,
   "id": 1178,
   "name": "Soothsayer",
   "mana": 4,
   "id": 109,
   "name": "Aegis Commander",
   "mana": 5,
   "id": 138,
   "name": "Hallowed Keeper",
   "mana": 6,
   "id": 1035,
   "name": "Rune Viper Tincture",
   "mana": 5,
   "id": 1036,
   "name": "Leyhoard Hatchling",
   "mana": 10,
   "id": 1042,
   "name": "Overgrown Rhino",
   "mana": 4,
   "id": 1253,
   "name": "Dart Maniac",
   "mana": 2,
   "id": 100132,
   "name": "Ancient Guardian",
   "mana": 2,
   "id": 1139,
   "name": "Trojan Battlemage",
   "mana": 3,
   "id": 100127,
   "name": "Magebolt",
   "mana": 2,
   "id": 100128,
   "name": "Amazon Recruit",
   "mana": 1,
   "id": 945,
   "name": "Blessing of War",
   "mana": 3,
   "id": 100920,
   "name": "First Pillar",
   "mana": 4,
   "id": 87012,
   "name": "Radiant Spirit",
   "mana": 4,
   "id": 11,
   "name": "Gloam Druid",
   "mana": 2,
   "id": 12,
   "name": "Sanctify",
   "mana": 2,
   "id": 21,
   "name": "Osiris, the Eternal",
   "mana": 3,
   "id": 22,
   "name": "Anubis, Guide of Souls",
   "mana": 6,
   "id": 23,
   "name": "Portal Wrangler",
   "mana": 4,
   "id": 51,
   "name": "Rebirth Planetar",
   "mana": 7,
   "id": 53,
   "name": "Dire Demilich",
   "mana": 7,
   "id": 153,
   "name": "Fanatic of Khnum",
   "mana": 2,
   "id": 340,
   "name": "Back-Alley Vendor",
   "mana": 1,
   "id": 1209,
   "name": "The Portable Fortress",
   "mana": 2,
   "id": 1103,
   "name": "Tomb Priest",
   "mana": 4,
   "id": 265,
   "name": "False Peace",
   "mana": 4,
   "id": 216,
   "name": "Ruthless Caipora",
   "mana": 5,
   "id": 294,
   "name": "Cavern Arachne",
   "mana": 5,
   "id": 1044,
   "name": "Staff of Roots",
   "mana": 2,
   "id": 1045,
   "name": "Marsh Walker",
   "mana": 1,
   "id": 1026,
   "name": "Lokian Disciple",
   "mana": 7,
   "id": 1101,
   "name": "Wildfire",
   "mana": 4,
   "id": 100134,
   "name": "Rogue Skulker",
   "mana": 1,
   "id": 87060,
   "name": "Just a Nibble",
   "mana": 2,
   "id": 54,
   "name": "Scarab Swarm",
   "mana": 1,
   "id": 76,
   "name": "Set Oshi",
   "mana": 6,
   "id": 33,
   "name": "Sentinel Princess",
   "mana": 1,
   "id": 114,
   "name": "Tutankhamun",
   "mana": 4,
   "id": 55,
   "name": "Boost Walker",
   "mana": 4,
   "id": 100135,
   "name": "Netherling",
   "mana": 2,
   "id": 122,
   "name": "Tomb Robber",
   "mana": 3,
   "id": 123,
   "name": "Friendly Mimic",
   "mana": 4,
   "id": 826,
   "name": "Selena, Champion of Nature",
   "mana": 4,
   "id": 1161,
   "name": "Amazon Conscript",
   "mana": 1,
   "id": 77,
   "name": "Enraged Ally",
   "mana": 2,
   "id": 124,
   "name": "Fusing Fleshspawn",
   "mana": 1,
   "id": 150,
   "name": "Nephthys Guardian",
   "mana": 6,
   "id": 217,
   "name": "Grass Roots",
   "mana": 3,
   "id": 1248,
   "name": "Assistant Alchemist",
   "mana": 1,
   "id": 1250,
   "name": "Street Conjuror",
   "mana": 1,
   "id": 100133,
   "name": "Ancient Executioner",
   "mana": 3,
   "id": 100136,
   "name": "Bodyguard",
   "mana": 1,
   "id": 906,
   "name": "Guardian of the Underworld",
   "mana": 8,
   "id": 78,
   "name": "Annoying Combatant",
   "mana": 5,
   "id": 100137,
   "name": "Hyena",
   "mana": 1,
   "id": 171,
   "name": "Will O' Wisp",
   "mana": 2,
   "id": 101305,
   "name": "Temnys of Thebia, Chronicler",
   "mana": 1,
   "id": 172,
   "name": "Wild Spellsinger",
   "mana": 6,
   "id": 1027,
   "name": "Slip Blade",
   "mana": 5,
   "id": 820,
   "name": "Form of Power",
   "mana": 1,
   "id": 907,
   "name": "Shadow of Lethenon",
   "mana": 1,
   "id": 87039,
   "name": "Peacebringer",
   "mana": 8,
   "id": 87040,
   "name": "Brilliant Intervention",
   "mana": 2,
   "id": 8,
   "name": "Eternal Servant",
   "mana": 3,
   "id": 100139,
   "name": "Demonic Skull",
   "mana": 10,
   "id": 191,
   "name": "Roadside Outfitter",
   "mana": 4,
   "id": 1051,
   "name": "Grendel, Night Terror",
   "mana": 8,
   "id": 1052,
   "name": "Warmonger Smith",
   "mana": 2,
   "id": 100156,
   "name": "Strong Malfunctioning Artifice",
   "mana": 1,
   "id": 385,
   "name": "Firewall",
   "mana": 4,
   "id": 1077,
   "name": "Trial Spirit",
   "mana": 1,
   "id": 15,
   "name": "Respected Jarl",
   "mana": 2,
   "id": 192,
   "name": "Actuary of War",
   "mana": 4,
   "id": 1162,
   "name": "Singsong Satyr",
   "mana": 4,
   "id": 91,
   "name": "Magic Inks",
   "mana": 2,
   "id": 1208,
   "name": "Mammon's Stalwart",
   "mana": 6,
   "id": 100138,
   "name": "Netherspawn",
   "mana": 6,
   "id": 100140,
   "name": "Battlethrall",
   "mana": 1,
   "id": 391,
   "name": "Howler Golem",
   "mana": 7,
   "id": 100141,
   "name": "Huscarl",
   "mana": 1,
   "id": 837,
   "name": "Enchanted Vines",
   "mana": 6,
   "id": 154,
   "name": "Mirror, Mirror",
   "mana": 1,
   "id": 52,
   "name": "Farsight Explorer",
   "mana": 2,
   "id": 79,
   "name": "Hunger Daemon",
   "mana": 3,
   "id": 935,
   "name": "Guild Siren",
   "mana": 2,
   "id": 409,
   "name": "Rat of Destruction",
   "mana": 1,
   "id": 325,
   "name": "Mindful Orc",
   "mana": 3,
   "id": 331,
   "name": "Identity Thief",
   "mana": 7,
   "id": 87043,
   "name": "Pluck From Fate",
   "mana": 3,
   "id": 87044,
   "name": "Crook of Shepherding",
   "mana": 2,
   "id": 410,
   "name": "Rat of Healing",
   "mana": 1,
   "id": 18,
   "name": "Levitate",
   "mana": 1,
   "id": 92,
   "name": "Runic Familiar",
   "mana": 2,
   "id": 166,
   "name": "The Nether Prince",
   "mana": 6,
   "id": 181,
   "name": "Daemonic Offering",
   "mana": 3,
   "id": 351,
   "name": "Archimedes Mirror",
   "mana": 6,
   "id": 100006,
   "name": "Larceny",
   "mana": 2,
   "id": 100008,
   "name": "Seer",
   "mana": 2,
   "id": 1049,
   "name": "Gersemi, Freyja's Spear",
   "mana": 3,
   "id": 1053,
   "name": "Devouring Blade",
   "mana": 4,
   "id": 1054,
   "name": "Chalice Priest",
   "mana": 2,
   "id": 1055,
   "name": "Radiant Embalmer",
   "mana": 4,
   "id": 411,
   "name": "Rat of Sorcery",
   "mana": 1,
   "id": 412,
   "name": "Rat of Perplexion",
   "mana": 1,
   "id": 100005,
   "name": "Blight",
   "mana": 2,
   "id": 100129,
   "name": "Walking Tree",
   "mana": 2,
   "id": 1110,
   "name": "Echophon, Atlantean Hydra",
   "mana": 9,
   "id": 100130,
   "name": "Impling",
   "mana": 1,
   "id": 100040,
   "name": "Rockdrake",
   "mana": 5,
   "id": 100063,
   "name": "Malfunctioning Artifice",
   "mana": 1,
   "id": 1002,
   "name": "Avalanche Strike",
   "mana": 2,
   "id": 1090,
   "name": "Minotaur Phalanx",
   "mana": 6,
   "id": 1251,
   "name": "Prescient Spellbinder",
   "mana": 3,
   "id": 98,
   "name": "The Sky Reaver",
   "mana": 5,
   "id": 1252,
   "name": "Living Container",
   "mana": 2,
   "id": 148,
   "name": "Cambion Runelord",
   "mana": 7,
   "id": 151,
   "name": "The Gatekeeper",
   "mana": 8,
   "id": 180,
   "name": "Planetar Envoy",
   "mana": 6,
   "id": 195,
   "name": "Cyclops",
   "mana": 6,
   "id": 196,
   "name": "Master Tactician",
   "mana": 2,
   "id": 198,
   "name": "War, Incarnate",
   "mana": 7,
   "id": 212,
   "name": "Alexis, Archon's Sword",
   "mana": 8,
   "id": 238,
   "name": "Outcast Amazon",
   "mana": 3,
   "id": 249,
   "name": "Netherborne Binder",
   "mana": 1,
   "id": 264,
   "name": "Odin's Whiteraven",
   "mana": 2,
   "id": 267,
   "name": "Sarcophagus",
   "mana": 2,
   "id": 270,
   "name": "Jungle Scout",
   "mana": 3,
   "id": 313,
   "name": "Engaged Enchanter",
   "mana": 2,
   "id": 346,
   "name": "Scales of Justice",
   "mana": 1,
   "id": 349,
   "name": "Shadow Slash",
   "mana": 4,
   "id": 100007,
   "name": "Shine",
   "mana": 2,
   "id": 100131,
   "name": "Skeleton",
   "mana": 1,
   "id": 400,
   "name": "First Phoenix",
   "mana": 5,
   "id": 800,
   "name": "Nether's Advocate",
   "mana": 2,
   "id": 802,
   "name": "Forbidden Experiment",
   "mana": 1,
   "id": 100036,
   "name": "Sentient Flameblades",
   "mana": 0,
   "id": 100037,
   "name": "Phoenix Egg",
   "mana": 1,
   "id": 87047,
   "name": "Escaped Silverback",
   "mana": 5,
   "id": 407,
   "name": "Philosophic Evangelist",
   "mana": 3,
   "id": 413,
   "name": "Rat of Reinforcement",
   "mana": 1,
   "id": 414,
   "name": "Rat of Trickery",
   "mana": 1,
   "id": 97,
   "name": "Glass Cannon",
   "mana": 3,
   "id": 101,
   "name": "Heka's Enchantress",
   "mana": 1,
   "id": 140,
   "name": "Death Masque",
   "mana": 4,
   "id": 100048,
   "name": "Aching Disciple",
   "mana": 1,
   "id": 314,
   "name": "Warp Engineer",
   "mana": 2,
   "id": 100053,
   "name": "Rune of Fire",
   "mana": 2,
   "id": 1144,
   "name": "Athena's Conjurer",
   "mana": 6,
   "id": 804,
   "name": "Necronomics",
   "mana": 1,
   "id": 843,
   "name": "Steadfast Scout",
   "mana": 3,
   "id": 805,
   "name": "Soul Charlatan",
   "mana": 3,
   "id": 157,
   "name": "Furies",
   "mana": 7,
   "id": 200,
   "name": "Clone",
   "mana": 2,
   "id": 273,
   "name": "Rampaging Leviathan",
   "mana": 7,
   "id": 183,
   "name": "Leyline Djinn",
   "mana": 11,
   "id": 1059,
   "name": "Holy Enchanter",
   "mana": 4,
   "id": 1254,
   "name": "Ratify",
   "mana": 5,
   "id": 189,
   "name": "Iron Kopis",
   "mana": 5,
   "id": 7,
   "name": "Broken Harvester",
   "mana": 1,
   "id": 852,
   "name": "Hooded Figure",
   "mana": 5,
   "id": 86,
   "name": "Read The Leaves",
   "mana": 2,
   "id": 199,
   "name": "Shadow Scryer",
   "mana": 1,
   "id": 224,
   "name": "Ocular Fiend",
   "mana": 6,
   "id": 87053,
   "name": "Wildroot Staff",
   "mana": 5,
   "id": 100052,
   "name": "Concealed Anim",
   "mana": 2,
   "id": 274,
   "name": "Crush Construct",
   "mana": 6,
   "id": 275,
   "name": "Bearstrider",
   "mana": 4,
   "id": 358,
   "name": "Avatar of Magic",
   "mana": 9,
   "id": 100142,
   "name": "Propyrean Owl",
   "mana": 3,
   "id": 90,
   "name": "Synergy Golem",
   "mana": 3,
   "id": 100054,
   "name": "Rune of Life",
   "mana": 2,
   "id": 1012,
   "name": "Starshard Bolt",
   "mana": 2,
   "id": 803,
   "name": "Return to the Cave",
   "mana": 1,
   "id": 17,
   "name": "Mimicus",
   "mana": 1,
   "id": 1047,
   "name": "Vinebound Jotun",
   "mana": 8,
   "id": 1102,
   "name": "Auric Mage",
   "mana": 6,
   "id": 806,
   "name": "Skull Scepter",
   "mana": 2,
   "id": 80,
   "name": "Overclock",
   "mana": 1,
   "id": 824,
   "name": "Lysander, Champion of Light",
   "mana": 6,
   "id": 81,
   "name": "Inflammable Imbecile",
   "mana": 1,
   "id": 186,
   "name": "Balance Summoner",
   "mana": 2,
   "id": 1017,
   "name": "Revivification",
   "mana": 1,
   "id": 1046,
   "name": "Faeflame Blade",
   "mana": 2,
   "id": 1050,
   "name": "Managarmr, Moon Hound",
   "mana": 3,
   "id": 87055,
   "name": "Stygian Collector",
   "mana": 4,
   "id": 1255,
   "name": "Umber Arrow",
   "mana": 2,
   "id": 107,
   "name": "Erratic Summons",
   "mana": 2,
   "id": 87042,
   "name": "Conversion",
   "mana": 4,
   "id": 14,
   "name": "Healing Insight",
   "mana": 1,
   "id": 108,
   "name": "Carcass Vulture",
   "mana": 2,
   "id": 182,
   "name": "High Thaumaturge",
   "mana": 2,
   "id": 16,
   "name": "Faustian Pact",
   "mana": 3,
   "id": 387,
   "name": "Protected Deamonbot",
   "mana": 5,
   "id": 353,
   "name": "Sign of Avarice",
   "mana": 4,
   "id": 388,
   "name": "Nethersaur",
   "mana": 6,
   "id": 830,
   "name": "Lysander's Spear",
   "mana": 3,
   "id": 831,
   "name": "Pallas' Wand",
   "mana": 2,
   "id": 184,
   "name": "Quicksilver Dragon",
   "mana": 7,
   "id": 193,
   "name": "Highborn Knight",
   "mana": 4,
   "id": 258,
   "name": "Hyksosian Chariot",
   "mana": 3,
   "id": 100004,
   "name": "Ruin",
   "mana": 2,
   "id": 1300,
   "name": "Undead Roach",
   "mana": 1,
   "id": 1013,
   "name": "Dust to Dust",
   "mana": 4,
   "id": 386,
   "name": "Shadow Banisher",
   "mana": 4,
   "id": 1034,
   "name": "Dreaming Sceptre",
   "mana": 3,
   "id": 1048,
   "name": "Valewarden Minotaur",
   "mana": 5,
   "id": 1056,
   "name": "Helios Guardian",
   "mana": 4,
   "id": 316,
   "name": "Well of Power",
   "mana": 5,
   "id": 1095,
   "name": "Dune Cavalry",
   "mana": 3,
   "id": 1096,
   "name": "Duergar Priest",
   "mana": 2,
   "id": 1230,
   "name": "Inconspicuous Carriage",
   "mana": 4,
   "id": 1240,
   "name": "Metamorphosis",
   "mana": 2,
   "id": 832,
   "name": "Selena's Bow",
   "mana": 3,
   "id": 2,
   "name": "Siren of the Grave",
   "mana": 1,
   "id": 1098,
   "name": "Felid Protector",
   "mana": 1,
   "id": 6,
   "name": "Ancient Curse",
   "mana": 3,
   "id": 1043,
   "name": "Nefarious Briar",
   "mana": 4,
   "id": 1210,
   "name": "Jinxblade Duelist",
   "mana": 3,
   "id": 829,
   "name": "Orfeo, Champion of Deception",
   "mana": 1,
   "id": 938,
   "name": "Blessing of Light",
   "mana": 2,
   "id": 87058,
   "name": "Soul Bargain",
   "mana": 1,
   "id": 106,
   "name": "Underbrush Boar",
   "mana": 2,
   "id": 206,
   "name": "Leviathan Hunter",
   "mana": 1,
   "id": 1060,
   "name": "Patience Priestess",
   "mana": 4,
   "id": 1061,
   "name": "Blind Martyr",
   "mana": 1,
   "id": 87071,
   "name": "Lambasting Wand",
   "mana": 2,
   "id": 32,
   "name": "Spellwrought Angel",
   "mana": 5,
   "id": 141,
   "name": "Underhand Thug",
   "mana": 3,
   "id": 41,
   "name": "Pocket Channeler",
   "mana": 5,
   "id": 87005,
   "name": "Vanguard Axewoman",
   "mana": 1,
   "id": 144,
   "name": "Tyr, The Just",
   "mana": 7,
   "id": 190,
   "name": "Ares' Eruption",
   "mana": 3,
   "id": 269,
   "name": "Mottled Ranger",
   "mana": 3,
   "id": 297,
   "name": "Dead Man's Flail",
   "mana": 4,
   "id": 145,
   "name": "Dread Queen Persephone",
   "mana": 6,
   "id": 146,
   "name": "Mistress Scythia",
   "mana": 3,
   "id": 1145,
   "name": "The Nemean Lion",
   "mana": 3,
   "id": 299,
   "name": "Blacksmith Armourer",
   "mana": 3,
   "id": 1062,
   "name": "Illuminated Warrior",
   "mana": 1,
   "id": 1100,
   "name": "Lightning Strike",
   "mana": 3,
   "id": 100103,
   "name": "Netherbeast",
   "mana": 4,
   "id": 1064,
   "name": "Ritual Rod",
   "mana": 1,
   "id": 1067,
   "name": "Atlant Phalanx",
   "mana": 5,
   "id": 1097,
   "name": "Shieldbearer",
   "mana": 1,
   "id": 1125,
   "name": "Made Mark",
   "mana": 1,
   "id": 1146,
   "name": "Judge Envoy",
   "mana": 7,
   "id": 1237,
   "name": "Serene Blade",
   "mana": 4,
   "id": 801,
   "name": "Diones, Spectral Sceptic",
   "mana": 3,
   "id": 100069,
   "name": "Heptaria, Manashard Fiend",
   "mana": 1,
   "id": 813,
   "name": "Academy Familiar",
   "mana": 1,
   "id": 100071,
   "name": "Rat",
   "mana": 0,
   "id": 833,
   "name": "Valka's Axe",
   "mana": 5,
   "id": 834,
   "name": "Neferu's Khopesh",
   "mana": 4,
   "id": 1301,
   "name": "Decaying Rhino",
   "mana": 4,
   "id": 1302,
   "name": "Cursed Obelisks",
   "mana": 5,
   "id": 1303,
   "name": "Mass Raise",
   "mana": 4,
   "id": 4,
   "name": "Influential Incubus",
   "mana": 3,
   "id": 30,
   "name": "Radiant Guardian",
   "mana": 7,
   "id": 158,
   "name": "Wizened Warlock",
   "mana": 3,
   "id": 31,
   "name": "Photogenesis",
   "mana": 7,
   "id": 185,
   "name": "Aquatic Torturer",
   "mana": 5,
   "id": 100072,
   "name": "Bomb",
   "mana": 0,
   "id": 838,
   "name": "Jaguar Staff",
   "mana": 5,
   "id": 1304,
   "name": "Corpse Explosion",
   "mana": 5,
   "id": 100125,
   "name": "Thievery",
   "mana": 2,
   "id": 1305,
   "name": "Outnumber the Living",
   "mana": 3,
   "id": 100160,
   "name": "Overgrown Golem",
   "mana": 3,
   "id": 393,
   "name": "The Iron Horse",
   "mana": 7,
   "id": 65003,
   "name": "Tethys",
   "mana": 9,
   "id": 322,
   "name": "Holy Writ",
   "mana": 2,
   "id": 100002,
   "name": "Atlas' Burden",
   "mana": 0,
   "id": 1111,
   "name": "Frost Giant Deadshot",
   "mana": 6,
   "id": 100073,
   "name": "Mana Bind",
   "mana": 3,
   "id": 87017,
   "name": "Summoner's Guide",
   "mana": 5,
   "id": 814,
   "name": "Rod of Rodents",
   "mana": 3,
   "id": 839,
   "name": "Dryad Seer",
   "mana": 2,
   "id": 854,
   "name": "Dream Stalker",
   "mana": 5,
   "id": 25,
   "name": "Odin, Endless War",
   "mana": 8,
   "id": 27,
   "name": "Ashen Drake",
   "mana": 7,
   "id": 817,
   "name": "Form of Unity",
   "mana": 3,
   "id": 87030,
   "name": "Twinhorn Rider",
   "mana": 7,
   "id": 87079,
   "name": "Spiked Tea",
   "mana": 4,
   "id": 237,
   "name": "Field Martyr",
   "mana": 3,
   "id": 241,
   "name": "Servant of Inti",
   "mana": 3,
   "id": 323,
   "name": "Anoint",
   "mana": 2,
   "id": 324,
   "name": "Reformation",
   "mana": 1,
   "id": 327,
   "name": "Canonize",
   "mana": 5,
   "id": 1005,
   "name": "Imperious Smite",
   "mana": 4,
   "id": 1011,
   "name": "Astric Implosion",
   "mana": 6,
   "id": 1021,
   "name": "Penitence",
   "mana": 7,
   "id": 1068,
   "name": "Helios Battlesworn",
   "mana": 5,
   "id": 1070,
   "name": "Eldritch Demonologist",
   "mana": 4,
   "id": 819,
   "name": "Archimea, Arithmancer",
   "mana": 5,
   "id": 898,
   "name": "Injured Hetairoi",
   "mana": 4,
   "id": 87011,
   "name": "Hoplite Initiate",
   "mana": 3,
   "id": 1306,
   "name": "The Plague",
   "mana": 8,
   "id": 247,
   "name": "Dragon Tooth Warrior",
   "mana": 5,
   "id": 87031,
   "name": "Fury",
   "mana": 1,
   "id": 301,
   "name": "Druidic Summons",
   "mana": 4,
   "id": 333,
   "name": "Needle-Fang Chameleon",
   "mana": 1,
   "id": 345,
   "name": "The Mastermind",
   "mana": 4,
   "id": 1099,
   "name": "Rampart",
   "mana": 1,
   "id": 840,
   "name": "Dionysian Bull",
   "mana": 6,
   "id": 87032,
   "name": "Vicious Rend",
   "mana": 1,
   "id": 1307,
   "name": "Eva, Baroness of the Dead",
   "mana": 2,
   "id": 848,
   "name": "Stolen Plans",
   "mana": 1,
   "id": 20,
   "name": "Dimension Looper",
   "mana": 4,
   "id": 384,
   "name": "Magic Missile Launcher",
   "mana": 4,
   "id": 811,
   "name": "Hippacria's Monster",
   "mana": 9,
   "id": 56,
   "name": "Pharaoh's Body-Double",
   "mana": 2,
   "id": 1124,
   "name": "Patron's Sacrament",
   "mana": 1,
   "id": 853,
   "name": "Satyr Hypnotist",
   "mana": 2,
   "id": 818,
   "name": "Majes, Spectral Philosopher",
   "mana": 5,
   "id": 1126,
   "name": "Tartessian Improviser",
   "mana": 1,
   "id": 66,
   "name": "Balance Ethereals",
   "mana": 6,
   "id": 380,
   "name": "Atlantean Rex",
   "mana": 6,
   "id": 381,
   "name": "Arcane Sphere",
   "mana": 1,
   "id": 28,
   "name": "Apate Conspirator",
   "mana": 1,
   "id": 272,
   "name": "Venerable Gryphon",
   "mana": 2,
   "id": 1113,
   "name": "Helian Blademaster",
   "mana": 6,
   "id": 321,
   "name": "Forty Days",
   "mana": 2,
   "id": 1308,
   "name": "Necroscepter",
   "mana": 3,
   "id": 96,
   "name": "Blade Trader Drosis",
   "mana": 3,
   "id": 844,
   "name": "Caller of the Hunt",
   "mana": 6,
   "id": 104,
   "name": "Raze Imp",
   "mana": 1,
   "id": 228,
   "name": "Empire's Footman",
   "mana": 2,
   "id": 277,
   "name": "Omnipresence",
   "mana": 3,
   "id": 300,
   "name": "Guerilla Sabotage",
   "mana": 3,
   "id": 306,
   "name": "Blood Rage",
   "mana": 2,
   "id": 389,
   "name": "Cryodyne Trident",
   "mana": 3,
   "id": 320,
   "name": "Pyroclastic Alchemist",
   "mana": 7,
   "id": 336,
   "name": "Kidnapper",
   "mana": 6,
   "id": 362,
   "name": "Dimension Door",
   "mana": 1,
   "id": 100044,
   "name": "Pyroclast",
   "mana": 1,
   "id": 1000,
   "name": "Dryder Sailweaver",
   "mana": 1,
   "id": 390,
   "name": "Golden Sabre",
   "mana": 2,
   "id": 395,
   "name": "Golden Golem",
   "mana": 5,
   "id": 859,
   "name": "Hierophant Silenus",
   "mana": 5,
   "id": 879,
   "name": "Isadora, Daring Patrician",
   "mana": 6,
   "id": 87001,
   "name": "Springbloom Hunter",
   "mana": 1,
   "id": 87002,
   "name": "Barricade",
   "mana": 2,
   "id": 87003,
   "name": "Dockside Prowler",
   "mana": 1,
   "id": 87033,
   "name": "Call to Arms",
   "mana": 3,
   "id": 1309,
   "name": "Netherswarm Lord",
   "mana": 5,
   "id": 87041,
   "name": "Commune With The Light",
   "mana": 3,
   "id": 1310,
   "name": "Rabid Bear",
   "mana": 3,
   "id": 1311,
   "name": "Feral Cat",
   "mana": 1,
   "id": 100009,
   "name": "Cultivate",
   "mana": 2,
   "id": 57,
   "name": "Swelling Boon",
   "mana": 5,
   "id": 821,
   "name": "Archvisionist",
   "mana": 5,
   "id": 59,
   "name": "Expectant Chicken",
   "mana": 1,
   "id": 58,
   "name": "Nullmaw",
   "mana": 5,
   "id": 147,
   "name": "Arius, Augur Paroxysm",
   "mana": 9,
   "id": 845,
   "name": "Seasonal Rebirth",
   "mana": 7,
   "id": 846,
   "name": "Dionysus, the Bountiful",
   "mana": 9,
   "id": 880,
   "name": "Tartessian Sentry",
   "mana": 4,
   "id": 887,
   "name": "Frumentarii Researcher",
   "mana": 3,
   "id": 307,
   "name": "Out of Its Misery",
   "mana": 1,
   "id": 1088,
   "name": "Cyclops Defender",
   "mana": 7,
   "id": 1089,
   "name": "Stormstress",
   "mana": 6,
   "id": 1112,
   "name": "Onyx Nightblade",
   "mana": 2,
   "id": 308,
   "name": "Take Them All On",
   "mana": 2,
   "id": 904,
   "name": "Ghostly Chariot",
   "mana": 3,
   "id": 905,
   "name": "Hydna, Reef Raider",
   "mana": 5,
   "id": 309,
   "name": "Demoralise",
   "mana": 1,
   "id": 1127,
   "name": "Cardshark",
   "mana": 1,
   "id": 1135,
   "name": "A Toast To Peace",
   "mana": 6,
   "id": 1183,
   "name": "Annoying Bureaucrat",
   "mana": 6,
   "id": 1008,
   "name": "Rapture Dance",
   "mana": 6,
   "id": 1233,
   "name": "Fickle Cambion",
   "mana": 3,
   "id": 823,
   "name": "Arcane Burst",
   "mana": 7,
   "id": 903,
   "name": "Pious Giant",
   "mana": 6,
   "id": 1184,
   "name": "Tomb Blademaster",
   "mana": 7,
   "id": 943,
   "name": "Blessing of Nature",
   "mana": 1,
   "id": 87069,
   "name": "Mind Jolt",
   "mana": 5,
   "id": 100090,
   "name": "Hand Axe",
   "mana": 0,
   "id": 1314,
   "name": "Moonbeam",
   "mana": 3,
   "id": 403,
   "name": "Blessed Ibis",
   "mana": 7,
   "id": 1312,
   "name": "Moon-Crazed Cyclops",
   "mana": 4,
   "id": 1313,
   "name": "Sip from the Spring",
   "mana": 3,
   "id": 19,
   "name": "Mountain Greatwyrm",
   "mana": 7,
   "id": 26,
   "name": "Valkyrie Heartsworn",
   "mana": 1,
   "id": 87009,
   "name": "Hunt Warden",
   "mana": 3,
   "id": 1033,
   "name": "Cerberus, Styx Hound",
   "mana": 7,
   "id": 87010,
   "name": "Jailbeast",
   "mana": 3,
   "id": 1315,
   "name": "Spring's Harvest",
   "mana": 4,
   "id": 1316,
   "name": "Sudden Bloom",
   "mana": 6,
   "id": 42,
   "name": "Dread Pirate",
   "mana": 2,
   "id": 828,
   "name": "Neferu, Champion of Death",
   "mana": 6,
   "id": 82,
   "name": "Light, Ascended",
   "mana": 6,
   "id": 87016,
   "name": "Riled Ursine",
   "mana": 5,
   "id": 1317,
   "name": "Finnian Fruitbearer",
   "mana": 2,
   "id": 1319,
   "name": "Guerilla Gardener",
   "mana": 8,
   "id": 225,
   "name": "Deathwish Thanetar",
   "mana": 16,
   "id": 262,
   "name": "Mark of the Warden",
   "mana": 2,
   "id": 315,
   "name": "Lord of Whispers",
   "mana": 4,
   "id": 83,
   "name": "Death, Unborn",
   "mana": 8,
   "id": 132,
   "name": "Namebinder Zal'zie",
   "mana": 1,
   "id": 326,
   "name": "Devout Cleric",
   "mana": 1,
   "id": 335,
   "name": "Reborn Pharaoh",
   "mana": 3,
   "id": 1078,
   "name": "Deuteria, Manashard Mage",
   "mana": 1,
   "id": 1079,
   "name": "Sentient Amphora",
   "mana": 2,
   "id": 1140,
   "name": "Viking Bloodguard",
   "mana": 3,
   "id": 825,
   "name": "Pallas, Champion of Magic",
   "mana": 3,
   "id": 337,
   "name": "Pandora, The Curious",
   "mana": 4,
   "id": 849,
   "name": "Fevered Dreams",
   "mana": 3,
   "id": 46,
   "name": "Untold Greed",
   "mana": 1,
   "id": 339,
   "name": "Locusta, Solution Expert",
   "mana": 6,
   "id": 143,
   "name": "Pixielock",
   "mana": 3,
   "id": 149,
   "name": "Tyet, Heir To The Sky",
   "mana": 9,
   "id": 1236,
   "name": "Light's Levy",
   "mana": 3,
   "id": 850,
   "name": "Obsidian Dagger",
   "mana": 3,
   "id": 851,
   "name": "Larcenous Pan",
   "mana": 2,
   "id": 261,
   "name": "Blessed Jackalope",
   "mana": 1,
   "id": 908,
   "name": "Dragon of the First Pillar",
   "mana": 7,
   "id": 910,
   "name": "Arkmonian Hydra",
   "mana": 7,
   "id": 1318,
   "name": "Moonlight Charm",
   "mana": 3,
   "id": 1320,
   "name": "Nokkvi Warrior",
   "mana": 1,
   "id": 34,
   "name": "Foolhardy Berserker",
   "mana": 2,
   "id": 911,
   "name": "Tartessian Mob",
   "mana": 7,
   "id": 35,
   "name": "Rolling Watcher",
   "mana": 2,
   "id": 38,
   "name": "Hurl Weapon",
   "mana": 1,
   "id": 342,
   "name": "Avatar of Deception",
   "mana": 4,
   "id": 912,
   "name": "Tartessian Pear",
   "mana": 4,
   "id": 45,
   "name": "Felid Tracker",
   "mana": 2,
   "id": 110,
   "name": "Reinforcements",
   "mana": 3,
   "id": 111,
   "name": "Soul Jar",
   "mana": 3,
   "id": 112,
   "name": "Rift Scholar",
   "mana": 5,
   "id": 118,
   "name": "Penitent Spear",
   "mana": 6,
   "id": 909,
   "name": "Antemion's Reflection",
   "mana": 5,
   "id": 87018,
   "name": "Rotting Mount",
   "mana": 6,
   "id": 1141,
   "name": "Dark Knives",
   "mana": 1,
   "id": 116,
   "name": "Devouring Golem",
   "mana": 5,
   "id": 187,
   "name": "Hooded Doppelganger",
   "mana": 6,
   "id": 343,
   "name": "Deception, Unshrouded",
   "mana": 7,
   "id": 352,
   "name": "Arcana-Daemon",
   "mana": 3,
   "id": 1086,
   "name": "Helian Elite",
   "mana": 8,
   "id": 60,
   "name": "Pallbearer",
   "mana": 3,
   "id": 61,
   "name": "Spellbound",
   "mana": 1,
   "id": 88,
   "name": "Shady Merchant",
   "mana": 3,
   "id": 1119,
   "name": "Makeshift Shiv",
   "mana": 1,
   "id": 1142,
   "name": "Ares' Runeblade",
   "mana": 8,
   "id": 1143,
   "name": "Arrow of Rage",
   "mana": 2,
   "id": 1147,
   "name": "Felid Janissary",
   "mana": 2,
   "id": 1148,
   "name": "Battle Aurochs",
   "mana": 3,
   "id": 392,
   "name": "Hasty Trade",
   "mana": 3,
   "id": 835,
   "name": "Orfeo's Mask",
   "mana": 5,
   "id": 857,
   "name": "Elixir of the Snake",
   "mana": 6,
   "id": 858,
   "name": "Eris, Queen of Chaos",
   "mana": 9,
   "id": 915,
   "name": "Council of the Gods",
   "mana": 2,
   "id": 916,
   "name": "The Trial Begins",
   "mana": 3,
   "id": 1149,
   "name": "Hector, Prince of Troy",
   "mana": 7,
   "id": 1321,
   "name": "Revered Seer",
   "mana": 4,
   "id": 944,
   "name": "Sudden Rally",
   "mana": 3,
   "id": 87004,
   "name": "Wild Hog",
   "mana": 1,
   "id": 87019,
   "name": "Hired Muscle",
   "mana": 6,
   "id": 1322,
   "name": "Inspiring Skald",
   "mana": 2,
   "id": 1323,
   "name": "Bar Fight",
   "mana": 1,
   "id": 1150,
   "name": "Spartan",
   "mana": 3,
   "id": 1199,
   "name": "Pacifism",
   "mana": 2,
   "id": 836,
   "name": "Frenzied Ritual",
   "mana": 4,
   "id": 860,
   "name": "Bloodthirsty Spear",
   "mana": 1,
   "id": 1324,
   "name": "Another Round!",
   "mana": 4,
   "id": 63,
   "name": "Uproot",
   "mana": 2,
   "id": 64,
   "name": "Avatar of Light",
   "mana": 7,
   "id": 919,
   "name": "Trial of the Shadows",
   "mana": 7,
   "id": 921,
   "name": "Trial of the False Reflection",
   "mana": 7,
   "id": 922,
   "name": "Trial of the Hydra",
   "mana": 5,
   "id": 815,
   "name": "Aether Herald",
   "mana": 2,
   "id": 816,
   "name": "Recovered Knowledge",
   "mana": 3,
   "id": 822,
   "name": "Mana Auditor",
   "mana": 6,
   "id": 861,
   "name": "Might Makes Right",
   "mana": 4,
   "id": 923,
   "name": "Trial of the Innocents",
   "mana": 6,
   "id": 925,
   "name": "Orfeo's Guile",
   "mana": 7,
   "id": 928,
   "name": "Selena's Insight",
   "mana": 6,
   "id": 929,
   "name": "Valka's Discovery",
   "mana": 3,
   "id": 87021,
   "name": "Juggernewt",
   "mana": 7,
   "id": 87034,
   "name": "Over-proof Brew",
   "mana": 5,
   "id": 65,
   "name": "Pickpocket",
   "mana": 4,
   "id": 120,
   "name": "Astraea's Envoy",
   "mana": 6,
   "id": 121,
   "name": "Agrodor Protector",
   "mana": 4,
   "id": 125,
   "name": "Enflame Self",
   "mana": 1,
   "id": 126,
   "name": "A Real Man",
   "mana": 1,
   "id": 43,
   "name": "Simple Satyr",
   "mana": 1,
   "id": 276,
   "name": "Vile Mantis",
   "mana": 4,
   "id": 1107,
   "name": "Pharaoh's Guard",
   "mana": 4,
   "id": 1151,
   "name": "Ogre Archer",
   "mana": 5,
   "id": 1153,
   "name": "Time-Bomb",
   "mana": 2,
   "id": 1325,
   "name": "Spoils of War",
   "mana": 1,
   "id": 1163,
   "name": "Zaxiom, Cryptic Panther",
   "mana": 5,
   "id": 1166,
   "name": "Bladefly",
   "mana": 4,
   "id": 382,
   "name": "Pyrocannon",
   "mana": 1,
   "id": 383,
   "name": "Aetherrust",
   "mana": 4,
   "id": 862,
   "name": "Commander's Gladius",
   "mana": 2,
   "id": 36,
   "name": "Natural Selection",
   "mana": 2,
   "id": 1326,
   "name": "Thunder Caller",
   "mana": 3,
   "id": 67,
   "name": "Golem Centurion",
   "mana": 7,
   "id": 68,
   "name": "Petard \"Elder\"",
   "mana": 3,
   "id": 70,
   "name": "Greed Banestrider",
   "mana": 3,
   "id": 71,
   "name": "Ragnarok",
   "mana": 1,
   "id": 1164,
   "name": "Tomb Torchbearer",
   "mana": 1,
   "id": 1327,
   "name": "Rage-Filled Hammer",
   "mana": 2,
   "id": 1328,
   "name": "Caged Berserker",
   "mana": 5,
   "id": 152,
   "name": "Odysseus, Tried Victor",
   "mana": 5,
   "id": 201,
   "name": "Mugging",
   "mana": 2,
   "id": 1155,
   "name": "Carthaginian Marine",
   "mana": 4,
   "id": 1167,
   "name": "Jungle Princess",
   "mana": 5,
   "id": 1169,
   "name": "Wiccan Warrior",
   "mana": 1,
   "id": 65000,
   "name": "Hyperion",
   "mana": 1,
   "id": 807,
   "name": "Ataraxia",
   "mana": 4,
   "id": 810,
   "name": "Cruel Overseer",
   "mana": 3,
   "id": 867,
   "name": "Strength In Numbers",
   "mana": 7,
   "id": 868,
   "name": "Bladesworn Warrior",
   "mana": 4,
   "id": 931,
   "name": "Soul Shatter",
   "mana": 3,
   "id": 87022,
   "name": "Anubian Usher",
   "mana": 7,
   "id": 87025,
   "name": "Reckless Flamebreather",
   "mana": 8,
   "id": 87026,
   "name": "Apep's Doomcaller",
   "mana": 8,
   "id": 75,
   "name": "Possessive Toupee",
   "mana": 1,
   "id": 127,
   "name": "Corrupt Ceremony",
   "mana": 1,
   "id": 128,
   "name": "Cudgel of Atonement",
   "mana": 1,
   "id": 1156,
   "name": "Inspirator",
   "mana": 2,
   "id": 194,
   "name": "Raving Fan",
   "mana": 1,
   "id": 1168,
   "name": "Oliphaunt Mount",
   "mana": 7,
   "id": 197,
   "name": "Returned Einherjar",
   "mana": 5,
   "id": 1154,
   "name": "Runed Asp",
   "mana": 2,
   "id": 1170,
   "name": "Tartessian Skirmisher",
   "mana": 3,
   "id": 100143,
   "name": "Destructive Dagger",
   "mana": 2,
   "id": 401,
   "name": "Light's Bidding",
   "mana": 6,
   "id": 402,
   "name": "Blessed Chimera",
   "mana": 7,
   "id": 65001,
   "name": "Prometheus",
   "mana": 6,
   "id": 65002,
   "name": "Atlas",
   "mana": 7,
   "id": 100000,
   "name": "Promethean Flame",
   "mana": 1,
   "id": 87028,
   "name": "Raid Reveller",
   "mana": 3,
   "id": 1329,
   "name": "Shackled Acolyte",
   "mana": 3,
   "id": 812,
   "name": "Form of Wisdom",
   "mana": 2,
   "id": 1330,
   "name": "Inconspicuous Bush",
   "mana": 4,
   "id": 73,
   "name": "Golem Excavator",
   "mana": 7,
   "id": 74,
   "name": "Recursion",
   "mana": 2,
   "id": 130,
   "name": "Mana Thief",
   "mana": 5,
   "id": 932,
   "name": "Blessing of Death",
   "mana": 2,
   "id": 933,
   "name": "Blessing of Deception",
   "mana": 2,
   "id": 87024,
   "name": "Achillean Dedicant",
   "mana": 8,
   "id": 1331,
   "name": "Gorgon Gargoyle",
   "mana": 2,
   "id": 1332,
   "name": "Changing Locks",
   "mana": 1,
   "id": 1333,
   "name": "Prisoner Exchange",
   "mana": 1,
   "id": 105,
   "name": "Pilgrim of the Cause",
   "mana": 2,
   "id": 375,
   "name": "Jaguar Rider",
   "mana": 4,
   "id": 49,
   "name": "The Black Argo",
   "mana": 5,
   "id": 209,
   "name": "Paragon of Fortune",
   "mana": 6,
   "id": 219,
   "name": "Nimble Pixie",
   "mana": 1,
   "id": 244,
   "name": "Aetherfuel Alchemist",
   "mana": 6,
   "id": 1114,
   "name": "Redfume Serum",
   "mana": 5,
   "id": 1115,
   "name": "Hunting Trap",
   "mana": 2,
   "id": 1116,
   "name": "Exorcise",
   "mana": 5,
   "id": 864,
   "name": "Mountain Raider",
   "mana": 4,
   "id": 245,
   "name": "Pyrrhic Incantation",
   "mana": 1,
   "id": 248,
   "name": "Reflection Elementalist",
   "mana": 5,
   "id": 283,
   "name": "Hypnos Puzzle Box",
   "mana": 1,
   "id": 354,
   "name": "Sucella",
   "mana": 7,
   "id": 355,
   "name": "Eager Gryphon",
   "mana": 2,
   "id": 100039,
   "name": "Brash Chicken",
   "mana": 1,
   "id": 100065,
   "name": "Skeletal Guard",
   "mana": 1,
   "id": 841,
   "name": "Ornery Goat",
   "mana": 3,
   "id": 842,
   "name": "Figure in the Streets",
   "mana": 8,
   "id": 863,
   "name": "Nokkvi Pillager",
   "mana": 3,
   "id": 865,
   "name": "Valknir Weaponsmith",
   "mana": 5,
   "id": 87006,
   "name": "Volatile Imp",
   "mana": 1,
   "id": 1334,
   "name": "Surprise Delivery",
   "mana": 3,
   "id": 357,
   "name": "Myrto's Daughter",
   "mana": 5,
   "id": 365,
   "name": "Hippolyta, Divided",
   "mana": 6,
   "id": 1117,
   "name": "Canopy Barrage",
   "mana": 2,
   "id": 866,
   "name": "Howling Berserker",
   "mana": 9,
   "id": 936,
   "name": "Battle Priest",
   "mana": 3,
   "id": 937,
   "name": "Healing Light",
   "mana": 4,
   "id": 939,
   "name": "Planetar Sage",
   "mana": 4,
   "id": 1335,
   "name": "Stoneskin Poison",
   "mana": 1,
   "id": 1336,
   "name": "Lantern-Bound Fae",
   "mana": 5,
   "id": 29,
   "name": "Hephaestus, The Enchanter",
   "mana": 4,
   "id": 40,
   "name": "Ruins Explorer",
   "mana": 2,
   "id": 93,
   "name": "Hall of Mirrors",
   "mana": 1,
   "id": 374,
   "name": "Backstreet Bouncer",
   "mana": 1,
   "id": 100042,
   "name": "Walking Plant",
   "mana": 1,
   "id": 940,
   "name": "Blessing of Magic",
   "mana": 2,
   "id": 1337,
   "name": "Cobra Scepter",
   "mana": 2,
   "id": 246,
   "name": "Trojan Golem",
   "mana": 2,
   "id": 359,
   "name": "Bucking Bronco",
   "mana": 5,
   "id": 1338,
   "name": "Patient Pickpocket",
   "mana": 1,
   "id": 100038,
   "name": "Chicken Egg",
   "mana": 1,
   "id": 89,
   "name": "Lupine Elemental",
   "mana": 5,
   "id": 95,
   "name": "That Which Aches",
   "mana": 6,
   "id": 100,
   "name": "Hercules, Son of Zeus",
   "mana": 7,
   "id": 251,
   "name": "Flying Carpet",
   "mana": 1,
   "id": 376,
   "name": "Iron-tooth Goblin",
   "mana": 2,
   "id": 377,
   "name": "Jackal",
   "mana": 2,
   "id": 1121,
   "name": "Anti-Magic Expert",
   "mana": 8,
   "id": 875,
   "name": "Parthene Democracy",
   "mana": 3,
   "id": 87007,
   "name": "Panacean Messenger",
   "mana": 2,
   "id": 87013,
   "name": "Poison Peddler",
   "mana": 4,
   "id": 87015,
   "name": "Flamecaller",
   "mana": 5,
   "id": 87020,
   "name": "Echocaster",
   "mana": 6,
   "id": 87035,
   "name": "Ramshackle Hatchet",
   "mana": 2,
   "id": 1339,
   "name": "Watchful Hound",
   "mana": 3,
   "id": 117,
   "name": "Runestorm",
   "mana": 5,
   "id": 136,
   "name": "Cyrene's Blessing",
   "mana": 2,
   "id": 100043,
   "name": "Broken Warrior",
   "mana": 1,
   "id": 1123,
   "name": "Guerilla Training",
   "mana": 2,
   "id": 1122,
   "name": "Mana Toad",
   "mana": 3,
   "id": 873,
   "name": "Veteran Hoplite",
   "mana": 1,
   "id": 1340,
   "name": "Inquisitor Informant",
   "mana": 2,
   "id": 1341,
   "name": "Righteous Apparition",
   "mana": 4,
   "id": 47,
   "name": "Sacred Lore",
   "mana": 3,
   "id": 174,
   "name": "Vine Armour",
   "mana": 3,
   "id": 48,
   "name": "Ignean Roulette",
   "mana": 1,
   "id": 50,
   "name": "Anputian Magus",
   "mana": 5,
   "id": 84,
   "name": "Arcane Transcendent",
   "mana": 3,
   "id": 94,
   "name": "Demogorgon",
   "mana": 7,
   "id": 250,
   "name": "Three's a Crowd",
   "mana": 6,
   "id": 252,
   "name": "Sleep Dart",
   "mana": 2,
   "id": 256,
   "name": "Burrowing Scarab",
   "mana": 2,
   "id": 259,
   "name": "Warden of Kauket",
   "mana": 8,
   "id": 305,
   "name": "Raiding Kraken",
   "mana": 9,
   "id": 872,
   "name": "Fortify",
   "mana": 2,
   "id": 874,
   "name": "Olympian Guard",
   "mana": 2,
   "id": 876,
   "name": "Field Medic",
   "mana": 1,
   "id": 87014,
   "name": "Underbridge Assailant",
   "mana": 4,
   "id": 137,
   "name": "Wrath Zealot",
   "mana": 7,
   "id": 1118,
   "name": "Firewine",
   "mana": 5,
   "id": 827,
   "name": "Valka, Champion of War",
   "mana": 9,
   "id": 87059,
   "name": "Feast on the Dead",
   "mana": 1,
   "id": 87062,
   "name": "Possessed Acolyte",
   "mana": 2,
   "id": 263,
   "name": "Crimson Oni",
   "mana": 4,
   "id": 278,
   "name": "Wilds Lifebonder",
   "mana": 2,
   "id": 330,
   "name": "Smoke Bomb",
   "mana": 4,
   "id": 100050,
   "name": "Protected Anim",
   "mana": 2,
   "id": 100051,
   "name": "Heavy Anim",
   "mana": 2,
   "id": 1152,
   "name": "Tamed Mammoth",
   "mana": 4,
   "id": 361,
   "name": "Loam Naturalist",
   "mana": 2,
   "id": 1157,
   "name": "Auric Rush",
   "mana": 1,
   "id": 1158,
   "name": "Switch Duelist",
   "mana": 1,
   "id": 87063,
   "name": "Third Eye Seer",
   "mana": 2,
   "id": 1342,
   "name": "Lips Are Sealed",
   "mana": 6,
   "id": 1343,
   "name": "Divine Judgement",
   "mana": 1,
   "id": 1344,
   "name": "Censure",
   "mana": 1,
   "id": 1348,
   "name": "Pillar of Lightning",
   "mana": 2,
   "id": 363,
   "name": "Sothek",
   "mana": 7,
   "id": 1159,
   "name": "Phylactery",
   "mana": 5,
   "id": 1345,
   "name": "Helios Justicar",
   "mana": 5,
   "id": 1349,
   "name": "Monolith of Storms",
   "mana": 5,
   "id": 1350,
   "name": "All-Seeing Spire",
   "mana": 4,
   "id": 1160,
   "name": "Athenian Archer",
   "mana": 1,
   "id": 1165,
   "name": "Infernal Footsoldier",
   "mana": 2,
   "id": 878,
   "name": "Bardelys, Parthene Orator",
   "mana": 3,
   "id": 260,
   "name": "Avatar of War",
   "mana": 8,
   "id": 296,
   "name": "Swashbuckler",
   "mana": 1,
   "id": 302,
   "name": "Lightfoot Informant",
   "mana": 2,
   "id": 1346,
   "name": "Writ of Law",
   "mana": 1,
   "id": 317,
   "name": "Inquisitor's Summons",
   "mana": 5,
   "id": 318,
   "name": "Lightdaemon King",
   "mana": 5,
   "id": 319,
   "name": "Griffith, The Chosen",
   "mana": 7,
   "id": 372,
   "name": "Crystallax",
   "mana": 5,
   "id": 100041,
   "name": "Injured Soldier",
   "mana": 1,
   "id": 100045,
   "name": "Box",
   "mana": 1,
   "id": 100046,
   "name": "Mirror",
   "mana": 1,
   "id": 100049,
   "name": "Iron Anim",
   "mana": 2,
   "id": 1347,
   "name": "Archpriest of Parthene",
   "mana": 7,
   "id": 1351,
   "name": "Stormfield",
   "mana": 5,
   "id": 1352,
   "name": "Safeguard Incantation",
   "mana": 2,
   "id": 1039,
   "name": "Frey, Archmage of Selene",
   "mana": 8,
   "id": 1040,
   "name": "Green Giant",
   "mana": 6,
   "id": 1041,
   "name": "Tainted Treant",
   "mana": 5,
   "id": 1174,
   "name": "Vrock",
   "mana": 3,
   "id": 329,
   "name": "Labyrinth Minotaur",
   "mana": 6,
   "id": 332,
   "name": "Heads or Tails",
   "mana": 2,
   "id": 100003,
   "name": "Orax, Shield of Pain",
   "mana": 4,
   "id": 877,
   "name": "Parthene Shieldmate",
   "mana": 3,
   "id": 913,
   "name": "Ludia's Deception",
   "mana": 1,
   "id": 87066,
   "name": "Rune Writer",
   "mana": 5,
   "id": 100035,
   "name": "Voyage To The Farlands",
   "mana": 1,
   "id": 1175,
   "name": "Veteran Archer",
   "mana": 4,
   "id": 115,
   "name": "Master of Surprises",
   "mana": 6,
   "id": 227,
   "name": "Hollow Pillager",
   "mana": 3,
   "id": 328,
   "name": "Angelic Veteran",
   "mana": 4,
   "id": 100056,
   "name": "Rune of Sight",
   "mana": 2,
   "id": 1038,
   "name": "Choralis Rune Moth",
   "mana": 3,
   "id": 1172,
   "name": "Traveling Bard",
   "mana": 4,
   "id": 881,
   "name": "Dowsing Blade",
   "mana": 1,
   "id": 882,
   "name": "Burden of Proof",
   "mana": 3,
   "id": 87067,
   "name": "Illuminate",
   "mana": 1,
   "id": 1353,
   "name": "Ghost Form",
   "mana": 2,
   "id": 869,
   "name": "Lead the Charge",
   "mana": 2,
   "id": 1173,
   "name": "Wicked Fae",
   "mana": 2,
   "id": 870,
   "name": "Hyrtacus, Brazen Hero",
   "mana": 6,
   "id": 883,
   "name": "Fated Arrival",
   "mana": 3,
   "id": 884,
   "name": "Aetheric Alarm",
   "mana": 3,
   "id": 87048,
   "name": "Charging Oryx",
   "mana": 7,
   "id": 1354,
   "name": "Modified Schematic",
   "mana": 2,
   "id": 87,
   "name": "Amplification Machine",
   "mana": 3,
   "id": 366,
   "name": "Merlin",
   "mana": 6,
   "id": 1355,
   "name": "Frostbitten Channeler",
   "mana": 2,
   "id": 1356,
   "name": "Scepter of Artistry",
   "mana": 3,
   "id": 3,
   "name": "Amazon Hearteater",
   "mana": 5,
   "id": 85,
   "name": "Gleeful Pillager",
   "mana": 2,
   "id": 368,
   "name": "Aeneas",
   "mana": 6,
   "id": 1176,
   "name": "Amazon Spearsoul",
   "mana": 2,
   "id": 1177,
   "name": "Hardened Channeler",
   "mana": 5,
   "id": 1357,
   "name": "Snowstorm Spire",
   "mana": 5,
   "id": 373,
   "name": "O Fortuna",
   "mana": 8,
   "id": 1180,
   "name": "Enduring Shield",
   "mana": 2,
   "id": 1129,
   "name": "End Times",
   "mana": 8,
   "id": 1179,
   "name": "Penthesilean Warrior",
   "mana": 5,
   "id": 344,
   "name": "Spellstealer",
   "mana": 5,
   "id": 347,
   "name": "Nightmare",
   "mana": 1,
   "id": 100047,
   "name": "Sleeper Golem",
   "mana": 3,
   "id": 159,
   "name": "Bulwark of the Sky",
   "mana": 7,
   "id": 266,
   "name": "Bonded Warrior",
   "mana": 2,
   "id": 298,
   "name": "Runaway Trebuchet",
   "mana": 5,
   "id": 304,
   "name": "The Harvester",
   "mana": 6,
   "id": 310,
   "name": "Equivalent Exchange",
   "mana": 3,
   "id": 348,
   "name": "Reap",
   "mana": 6,
   "id": 350,
   "name": "Beyond the Grave",
   "mana": 1,
   "id": 1128,
   "name": "Wiccan Trapper",
   "mana": 1,
   "id": 1181,
   "name": "Combat Medic",
   "mana": 3,
   "id": 1182,
   "name": "Spellsight Seer",
   "mana": 1,
   "id": 885,
   "name": "Helia, the Illuminator",
   "mana": 7,
   "id": 886,
   "name": "Ironclad Minotaur",
   "mana": 6,
   "id": 914,
   "name": "Aeona's Defection",
   "mana": 5,
   "id": 917,
   "name": "Vow of Champions",
   "mana": 2,
   "id": 918,
   "name": "Trial of the Underworld",
   "mana": 8,
   "id": 924,
   "name": "Neferu's Will",
   "mana": 5,
   "id": 927,
   "name": "Pallas' Incantation",
   "mana": 6,
   "id": 930,
   "name": "Priestess of Takhat",
   "mana": 1,
   "id": 367,
   "name": "Avatar of Nature",
   "mana": 5,
   "id": 369,
   "name": "Circe, Vengeful Sorceress",
   "mana": 7,
   "id": 934,
   "name": "Port Authority",
   "mana": 6,
   "id": 941,
   "name": "Spellbound Goblin",
   "mana": 4,
   "id": 942,
   "name": "Beast Speaker",
   "mana": 4,
   "id": 87073,
   "name": "Bedeviled Shadow",
   "mana": 3,
   "id": 1358,
   "name": "Cursed Hoplite",
   "mana": 3,
   "id": 370,
   "name": "Nature, Overgrown",
   "mana": 7,
   "id": 87074,
   "name": "Secrets Broker",
   "mana": 5,
   "id": 1359,
   "name": "Blood Armor",
   "mana": 1,
   "id": 1360,
   "name": "Pan Forgemaster",
   "mana": 4,
   "id": 1361,
   "name": "Mark of Death",
   "mana": 3,
   "id": 311,
   "name": "Arms Trafficker",
   "mana": 2,
   "id": 312,
   "name": "Salvaged Sentinel",
   "mana": 7,
   "id": 371,
   "name": "Specialist Force",
   "mana": 5,
   "id": 1362,
   "name": "Deathwatch Elder",
   "mana": 3,
   "id": 87050,
   "name": "Untamed Regrowth",
   "mana": 1,
   "id": 87052,
   "name": "Jump On!",
   "mana": 4,
   "id": 889,
   "name": "Fortified Acropolis",
   "mana": 6,
   "id": 890,
   "name": "Frumentarii Instigator",
   "mana": 4,
   "id": 891,
   "name": "Desert Mercenary",
   "mana": 3,
   "id": 87068,
   "name": "Versatile Conjuration",
   "mana": 3,
   "id": 892,
   "name": "Diligent Architect",
   "mana": 3,
   "id": 87070,
   "name": "Epiphany",
   "mana": 6,
   "id": 87072,
   "name": "Glider Assailant",
   "mana": 2,
   "id": 1370,
   "name": "The Rotted One",
   "mana": 5,
   "id": 1371,
   "name": "Takhat, the Forgotten",
   "mana": 7,
   "id": 1372,
   "name": "Arch of Amenmose",
   "mana": 6,
   "id": 1373,
   "name": "Plague Talisman",
   "mana": 4,
   "id": 1374,
   "name": "Voracious Fiend",
   "mana": 4,
   "id": 1375,
   "name": "Mutual Hatred",
   "mana": 3,
   "id": 1376,
   "name": "Miasmic Forge",
   "mana": 3,
   "id": 100057,
   "name": "Sterling Spear",
   "mana": 2,
   "id": 100059,
   "name": "Curative Cudgel",
   "mana": 2,
   "id": 893,
   "name": "Parthene Guardian",
   "mana": 2,
   "id": 87075,
   "name": "Wiznapper",
   "mana": 8,
   "id": 87077,
   "name": "Ransom",
   "mana": 4,
   "id": 1363,
   "name": "Inexorable Raider",
   "mana": 4,
   "id": 65004,
   "name": "Citadel of the Gods",
   "mana": 1,
   "id": 894,
   "name": "Satyr Outcast",
   "mana": 1,
   "id": 1364,
   "name": "Overseer of Vitality",
   "mana": 7,
   "id": 1365,
   "name": "Pull the Strings",
   "mana": 3,
   "id": 1366,
   "name": "Triage Necromancer",
   "mana": 5,
   "id": 1367,
   "name": "City Planner",
   "mana": 8,
   "id": 1368,
   "name": "Barbed Fly",
   "mana": 3,
   "id": 1369,
   "name": "Harrowing Visions",
   "mana": 4,
   "id": 895,
   "name": "Militant Extortionist",
   "mana": 1,
   "id": 896,
   "name": "Foreign Diplomat",
   "mana": 2,
   "id": 899,
   "name": "Thebian Strategos",
   "mana": 5,
   "id": 900,
   "name": "Student of Truth",
   "mana": 2,
   "id": 901,
   "name": "Student of Society",
   "mana": 1,
   "id": 902,
   "name": "Student of Blades",
   "mana": 3,
   "id": 87036,
   "name": "Battlement Luminary",
   "mana": 2,
   "id": 87049,
   "name": "Aspect of the Axolotl",
   "mana": 3,
   "id": 1377,
   "name": "Desecrated Shrine",
   "mana": 1,
   "id": 100884,
   "name": "Aetheric Echo",
   "mana": 1,
   "id": 156,
   "name": "Dwarven Smiths",
   "mana": 2,
   "id": 235,
   "name": "Wind-Up Roller",
   "mana": 2,
   "id": 257,
   "name": "La Bolefuego",
   "mana": 5,
   "id": 1057,
   "name": "Battle Cleric",
   "mana": 5,
   "id": 1058,
   "name": "Bright Mage",
   "mana": 3,
   "id": 1120,
   "name": "Vault Vagabond",
   "mana": 3,
   "id": 1132,
   "name": "The Old Ritual",
   "mana": 4,
   "id": 1185,
   "name": "Strix Hunter",
   "mana": 4,
   "id": 948,
   "name": "Divine Messenger",
   "mana": 7,
   "id": 949,
   "name": "Dragonkin Caller",
   "mana": 4,
   "id": 100910,
   "name": "Hydra Head",
   "mana": 2,
   "id": 87078,
   "name": "Stack the Deck",
   "mana": 5,
   "id": 87080,
   "name": "Poisoned Dagger",
   "mana": 4,
   "id": 1,
   "name": "Nethergram",
   "mana": 7,
   "id": 24,
   "name": "Midnight Cat",
   "mana": 1,
   "id": 99,
   "name": "Hades, Underworld Lord",
   "mana": 8,
   "id": 102,
   "name": "Me Two Three",
   "mana": 1,
   "id": 103,
   "name": "Shadow Prince",
   "mana": 7,
   "id": 119,
   "name": "Golden Harpe",
   "mana": 3,
   "id": 1186,
   "name": "The Hunt",
   "mana": 6,
   "id": 1187,
   "name": "Signal Scouts",
   "mana": 3,
   "id": 871,
   "name": "Xanthe of Tartessos",
   "mana": 3,
   "id": 888,
   "name": "Militant Gladiator",
   "mana": 5,
   "id": 950,
   "name": "Manticore Hulk",
   "mana": 4,
   "id": 100800,
   "name": "Experimental Outcome",
   "mana": 2,
   "id": 1378,
   "name": "Guardian Simulacrum",
   "mana": 6,
   "id": 1379,
   "name": "Magnetic Blast",
   "mana": 2,
   "id": 1380,
   "name": "Armadillo Familiar",
   "mana": 1,
   "id": 1381,
   "name": "Unproven Incantation",
   "mana": 4,
   "id": 139,
   "name": "Gentle Monk",
   "mana": 4,
   "id": 142,
   "name": "Chainflip",
   "mana": 3,
   "id": 360,
   "name": "Black Rhino",
   "mana": 6,
   "id": 1130,
   "name": "Brimstone",
   "mana": 1,
   "id": 1131,
   "name": "Blight Bomb",
   "mana": 1,
   "id": 1133,
   "name": "Ray of Disintegration",
   "mana": 5,
   "id": 1134,
   "name": "Void Flash",
   "mana": 4,
   "id": 1136,
   "name": "Deadly Arsenal",
   "mana": 1,
   "id": 1137,
   "name": "Reckoning",
   "mana": 1,
   "id": 1138,
   "name": "Viking Longship",
   "mana": 4,
   "id": 255,
   "name": "Master of Indulgences",
   "mana": 4,
   "id": 341,
   "name": "Merchant Prince",
   "mana": 4,
   "id": 37,
   "name": "Spiral Golem",
   "mana": 6,
   "id": 39,
   "name": "Arrest Warrant",
   "mana": 6,
   "id": 218,
   "name": "Proud Conscriptor",
   "mana": 4,
   "id": 220,
   "name": "Field Nurse",
   "mana": 1,
   "id": 231,
   "name": "Pyramid Warden",
   "mana": 2,
   "id": 232,
   "name": "Unruly Shredder",
   "mana": 2,
   "id": 233,
   "name": "Sonic Juggernaut",
   "mana": 5,
   "id": 100055,
   "name": "Rune of Strength",
   "mana": 2,
   "id": 100062,
   "name": "Mind Probe",
   "mana": 2,
   "id": 1004,
   "name": "Opalised Roots",
   "mana": 6,
   "id": 234,
   "name": "Guardian of the Gates",
   "mana": 3,
   "id": 236,
   "name": "Stun Gun Construct",
   "mana": 4,
   "id": 239,
   "name": "Bonepact Hunter",
   "mana": 4,
   "id": 240,
   "name": "Spelljam Shaman",
   "mana": 4,
   "id": 1006,
   "name": "Purification Filter",
   "mana": 6,
   "id": 1007,
   "name": "Darkdream Hex",
   "mana": 3,
   "id": 242,
   "name": "Advocate of Brilliance",
   "mana": 6,
   "id": 1188,
   "name": "Thaeric Blessing",
   "mana": 1,
   "id": 1189,
   "name": "Belligerent Warlock",
   "mana": 2,
   "id": 1382,
   "name": "Miraculous Familiar",
   "mana": 3,
   "id": 1383,
   "name": "Scholar of Power",
   "mana": 7,
   "id": 1384,
   "name": "Vortimer the Volatile",
   "mana": 3,
   "id": 243,
   "name": "Leywraith",
   "mana": 6,
   "id": 254,
   "name": "Primal Guidance",
   "mana": 1,
   "id": 1385,
   "name": "Crystal Watcher",
   "mana": 4,
   "id": 1386,
   "name": "Demetrios, Playwright",
   "mana": 2,
   "id": 1387,
   "name": "Lightning Talisman",
   "mana": 4,
   "id": 1388,
   "name": "Wall of Lightning",
   "mana": 4,
   "id": 1389,
   "name": "Labyrinth Guard",
   "mana": 6,
   "id": 293,
   "name": "Lore \u0026 Order Inspector",
   "mana": 1,
   "id": 1393,
   "name": "Volcanic Watcher",
   "mana": 1,
   "id": 1394,
   "name": "Enchanted Chariot",
   "mana": 1,
   "id": 1395,
   "name": "Aggravated Architect",
   "mana": 2,
   "id": 1396,
   "name": "Grumpy Chest",
   "mana": 3,
   "id": 44,
   "name": "Unnatural Binding",
   "mana": 1,
   "id": 62,
   "name": "Deathdealt Netherine",
   "mana": 6,
   "id": 295,
   "name": "Ferocious Rougarou",
   "mana": 5,
   "id": 1009,
   "name": "Netherwarp",
   "mana": 4,
   "id": 1397,
   "name": "Skeletal Hoplite",
   "mana": 1,
   "id": 1398,
   "name": "Polyhymnia, Aetheric Hydra",
   "mana": 9,
   "id": 1399,
   "name": "Phalanx Lieutenant",
   "mana": 5,
   "id": 1400,
   "name": "Strix Conscript",
   "mana": 3,
   "id": 1401,
   "name": "Planetar Acolyte",
   "mana": 1,
   "id": 268,
   "name": "Sphinx Cat",
   "mana": 4,
   "id": 271,
   "name": "Revenant Lynx",
   "mana": 3,
   "id": 1010,
   "name": "Blackblood Blast",
   "mana": 6,
   "id": 1014,
   "name": "Raise Dead",
   "mana": 5,
   "id": 1015,
   "name": "Staff of Shards",
   "mana": 2,
   "id": 1019,
   "name": "Antimagic Wards",
   "mana": 3,
   "id": 1020,
   "name": "Zealous March",
   "mana": 8,
   "id": 280,
   "name": "Laertes' Vendetta",
   "mana": 4,
   "id": 281,
   "name": "Red Fume Dash",
   "mana": 2,
   "id": 1022,
   "name": "Orcish Elite",
   "mana": 5,
   "id": 282,
   "name": "Rune Smuggler",
   "mana": 6,
   "id": 284,
   "name": "Dick Puddlecote",
   "mana": 3,
   "id": 285,
   "name": "Beam",
   "mana": 4,
   "id": 286,
   "name": "Rebel Quartermaster",
   "mana": 3,
   "id": 1023,
   "name": "Mercenary Troop",
   "mana": 4,
   "id": 1390,
   "name": "Vow of Learning",
   "mana": 3,
   "id": 1402,
   "name": "Dead Sentry",
   "mana": 4,
   "id": 1403,
   "name": "Blazing Behemoth",
   "mana": 7,
   "id": 1404,
   "name": "Divine Archon",
   "mana": 5,
   "id": 1405,
   "name": "Amazon Spellcatcher",
   "mana": 2,
   "id": 1406,
   "name": "Guild Enforcer",
   "mana": 6,
   "id": 287,
   "name": "The Cleansing",
   "mana": 3,
   "id": 288,
   "name": "Ra's Ascension",
   "mana": 4,
   "id": 289,
   "name": "Alms For Service",
   "mana": 1,
   "id": 290,
   "name": "Ambush",
   "mana": 3,
   "id": 291,
   "name": "Faraday Cage",
   "mana": 4,
   "id": 292,
   "name": "Gunpowder Plot",
   "mana": 4,
   "id": 1407,
   "name": "Thebian Elephant",
   "mana": 7,
   "id": 1391,
   "name": "Defend the Ramparts",
   "mana": 3,
   "id": 1392,
   "name": "Shaped Blast",
   "mana": 5,
   "id": 1433,
   "name": "Anubian Redeemer",
   "mana": 6,
   "id": 1434,
   "name": "Protective Benediction",
   "mana": 4,
   "id": 1435,
   "name": "Radiant Dawn",
   "mana": 7,
   "id": 1436,
   "name": "Armor Lurker",
   "mana": 2,
   "id": 1437,
   "name": "Grand Vault",
   "mana": 3,
   "id": 72,
   "name": "Scythes of the Harvest",
   "mana": 4,
   "id": 100060,
   "name": "Banished Shadow",
   "mana": 1,
   "id": 100061,
   "name": "Spirit Beast",
   "mana": 1,
   "id": 100064,
   "name": "Barbed Hook",
   "mana": 0,
   "id": 1001,
   "name": "Carnage Sweep",
   "mana": 5,
   "id": 1003,
   "name": "Arkmonian Onslaught",
   "mana": 5,
   "id": 1438,
   "name": "Piercing Bolt",
   "mana": 1,
   "id": 1408,
   "name": "Ogre Warlock",
   "mana": 4,
   "id": 1409,
   "name": "Tempest Giant",
   "mana": 6,
   "id": 1410,
   "name": "Covetous Cutthroat",
   "mana": 4,
   "id": 1411,
   "name": "Larcenous Imp",
   "mana": 2,
   "id": 1412,
   "name": "Bronze Gate",
   "mana": 3,
   "id": 1413,
   "name": "Munosian Infiltrator",
   "mana": 3,
   "id": 1414,
   "name": "Beam Sentry",
   "mana": 1,
   "id": 1415,
   "name": "Avraxus, the Gamekeeper",
   "mana": 2,
   "id": 1416,
   "name": "Venerable Paladin",
   "mana": 3,
   "id": 1417,
   "name": "Exalted Hermit",
   "mana": 2,
   "id": 1418,
   "name": "Shielded by Light",
   "mana": 3,
   "id": 1419,
   "name": "Illustrious Planetar",
   "mana": 3,
   "id": 1420,
   "name": "Zealous Ecclesiast",
   "mana": 2,
   "id": 1421,
   "name": "Excommunicate",
   "mana": 6,
   "id": 1422,
   "name": "Mentor of Salvation",
   "mana": 7,
   "id": 1423,
   "name": "Kadmos, Son of Lysander",
   "mana": 4,
   "id": 1424,
   "name": "Parthene Proscenium",
   "mana": 6,
   "id": 1425,
   "name": "Thaeriel's Anvil",
   "mana": 8,
   "id": 1426,
   "name": "Sern, The Moderator",
   "mana": 4,
   "id": 1427,
   "name": "Divine Chains",
   "mana": 6,
   "id": 1428,
   "name": "Generous Aid",
   "mana": 2,
   "id": 1429,
   "name": "Glaring Talisman",
   "mana": 4,
   "id": 1430,
   "name": "Golden-Winged Sphinx",
   "mana": 5,
   "id": 1431,
   "name": "Animated Armory",
   "mana": 4,
   "id": 1432,
   "name": "Empyrean Pacifist",
   "mana": 1,
   "id": 1439,
   "name": "Plate Pilferer",
   "mana": 4,
   "id": 1440,
   "name": "Handsome Devil",
   "mana": 5,
   "id": 1193,
   "name": "Bladecaster",
   "mana": 2,
   "id": 1194,
   "name": "Felid Assassin",
   "mana": 1,
   "id": 1195,
   "name": "Devoted Follower",
   "mana": 2,
   "id": 1196,
   "name": "Triumvirate Prophet",
   "mana": 3,
   "id": 1197,
   "name": "Tavern Brawler",
   "mana": 2,
   "id": 1198,
   "name": "Sentry Post",
   "mana": 2,
   "id": 1451,
   "name": "The Hollow",
   "mana": 2,
   "id": 1452,
   "name": "Twisting Talisman",
   "mana": 1,
   "id": 1453,
   "name": "Golden Curse",
   "mana": 4,
   "id": 1454,
   "name": "Helm Hustler",
   "mana": 3,
   "id": 1455,
   "name": "Giant Pangolin",
   "mana": 7,
   "id": 1456,
   "name": "Snapping Turtle",
   "mana": 6,
   "id": 1457,
   "name": "Aspect of the Pangolin",
   "mana": 4,
   "id": 1200,
   "name": "Cursed Caipora",
   "mana": 5,
   "id": 946,
   "name": "Valknir Zealot",
   "mana": 1,
   "id": 1458,
   "name": "Spiny Porcupine",
   "mana": 4,
   "id": 1459,
   "name": "Crescent Werewolf",
   "mana": 2,
   "id": 1460,
   "name": "Celestial Stag",
   "mana": 3,
   "id": 1024,
   "name": "Blade of Styx",
   "mana": 3,
   "id": 1025,
   "name": "Thalia, Charite Temptress",
   "mana": 6,
   "id": 1028,
   "name": "Famished Ghoul",
   "mana": 4,
   "id": 947,
   "name": "Fenris Berserker",
   "mana": 3,
   "id": 1029,
   "name": "Bombfly",
   "mana": 1,
   "id": 1441,
   "name": "Ludia's Dedicant",
   "mana": 3,
   "id": 1442,
   "name": "Pray to Win",
   "mana": 2,
   "id": 1443,
   "name": "Professor of Murder",
   "mana": 7,
   "id": 1444,
   "name": "Counterfeit",
   "mana": 2,
   "id": 1445,
   "name": "Demolitions Expert",
   "mana": 2,
   "id": 1030,
   "name": "Sand Scorpion",
   "mana": 5,
   "id": 1031,
   "name": "Vampiric Skull",
   "mana": 6,
   "id": 1032,
   "name": "Writhing Spirit",
   "mana": 1,
   "id": 1037,
   "name": "Oni Spellsword",
   "mana": 3,
   "id": 1446,
   "name": "Prison Escapee",
   "mana": 3,
   "id": 1447,
   "name": "Ring of the Siren",
   "mana": 3,
   "id": 1448,
   "name": "Scylla, Carnival Ringleader",
   "mana": 4,
   "id": 1449,
   "name": "Lady Marcella",
   "mana": 3,
   "id": 1450,
   "name": "Shadow Matriarch",
   "mana": 3,
   "id": 1461,
   "name": "New Growth",
   "mana": 2,
   "id": 1190,
   "name": "Recovering Sigil",
   "mana": 2,
   "id": 1191,
   "name": "Trapdoor",
   "mana": 2,
   "id": 1192,
   "name": "Aging Veteran",
   "mana": 2,
   "id": 207,
   "name": "Peculiar Spellwyrm",
   "mana": 1,
   "id": 1465,
   "name": "Sage of Renewal",
   "mana": 7,
   "id": 129,
   "name": "Avatar of Death",
   "mana": 6,
   "id": 134,
   "name": "Compost Charm",
   "mana": 2,
   "id": 253,
   "name": "Wasteful Shax",
   "mana": 2,
   "id": 855,
   "name": "Elixir of the Panther",
   "mana": 5,
   "id": 87056,
   "name": "Corpse Swallower",
   "mana": 6,
   "id": 334,
   "name": "Sharpen",
   "mana": 2,
   "id": 1066,
   "name": "Void Drake",
   "mana": 7,
   "id": 1069,
   "name": "Amplureal, Sentient Shard",
   "mana": 4,
   "id": 1071,
   "name": "Pyrrhic Adolescent",
   "mana": 4,
   "id": 1075,
   "name": "Solemn Lecturer",
   "mana": 4,
   "id": 1076,
   "name": "Battlebard",
   "mana": 1,
   "id": 394,
   "name": "Aether Chest",
   "mana": 3,
   "id": 856,
   "name": "Pan Marauder",
   "mana": 6,
   "id": 920,
   "name": "Trial of the First Pillar",
   "mana": 6,
   "id": 1466,
   "name": "Ominous Burrow",
   "mana": 7,
   "id": 926,
   "name": "Lysander's Mercy",
   "mana": 7,
   "id": 87027,
   "name": "Boil-Blood Outlaw",
   "mana": 1,
   "id": 87057,
   "name": "Necromantic",
   "mana": 8,
   "id": 1462,
   "name": "Brazen Moose",
   "mana": 5,
   "id": 1463,
   "name": "Low-Hanging Fruit",
   "mana": 1,
   "id": 13,
   "name": "Charm",
   "mana": 8,
   "id": 113,
   "name": "Anhotep the Embalmer",
   "mana": 7,
   "id": 131,
   "name": "Lara Grim, Spellthief",
   "mana": 1,
   "id": 133,
   "name": "Nemris, the Unstable",
   "mana": 6,
   "id": 1063,
   "name": "Asterius, Glittering One",
   "mana": 6,
   "id": 1065,
   "name": "Hallowing Light",
   "mana": 2,
   "id": 1072,
   "name": "Aether Battlescout",
   "mana": 3,
   "id": 1073,
   "name": "Dwarf Atlant",
   "mana": 3,
   "id": 808,
   "name": "Undead Chimera",
   "mana": 4,
   "id": 1467,
   "name": "Blood and Bone",
   "mana": 1,
   "id": 135,
   "name": "Fertility Idol",
   "mana": 7,
   "id": 1074,
   "name": "Pyrrhic Hatchling",
   "mana": 2,
   "id": 809,
   "name": "Deathwatch Curate",
   "mana": 5,
   "id": 847,
   "name": "Chiron, the Teacher",
   "mana": 1,
   "id": 1464,
   "name": "Falling Star",
   "mana": 5,
   "id": 1468,
   "name": "Starving Sabertooth",
   "mana": 4,
   "id": 1469,
   "name": "Raging Giant",
   "mana": 6,
   "id": 1470,
   "name": "Vicious Manticore",
   "mana": 5,
   "id": 176,
   "name": "Dense Fog",
   "mana": 1,
   "id": 177,
   "name": "Exoscout",
   "mana": 6,
   "id": 1472,
   "name": "Watchtower of Agrodor",
   "mana": 6,
   "id": 1473,
   "name": "Blazing Talisman",
   "mana": 4,
   "id": 1474,
   "name": "Hearts of Bronze",
   "mana": 2,
   "id": 155,
   "name": "Jason, Medea's Muse",
   "mana": 3,
   "id": 160,
   "name": "Dangerous Ritual",
   "mana": 2,
   "id": 161,
   "name": "Apocalypse Now",
   "mana": 7,
   "id": 162,
   "name": "Tormentor Fiend",
   "mana": 6,
   "id": 163,
   "name": "Mercenary Daemon",
   "mana": 5,
   "id": 164,
   "name": "Azure Djinni",
   "mana": 7,
   "id": 165,
   "name": "Incoming Raid",
   "mana": 4,
   "id": 178,
   "name": "Ancient Texts",
   "mana": 1,
   "id": 179,
   "name": "Trapdoor Assassin",
   "mana": 2,
   "id": 202,
   "name": "Shade Walker",
   "mana": 4,
   "id": 203,
   "name": "Ares Peacemaker",
   "mana": 4,
   "id": 204,
   "name": "Enduring Lemure",
   "mana": 4,
   "id": 205,
   "name": "Contagious Ghoul",
   "mana": 1,
   "id": 208,
   "name": "Thresher Bug",
   "mana": 2,
   "id": 1080,
   "name": "Balthazar, Blood Magus",
   "mana": 2,
   "id": 1081,
   "name": "Arkmonian Anteater",
   "mana": 1,
   "id": 1082,
   "name": "Tribal Orc",
   "mana": 1,
   "id": 1475,
   "name": "Looting Squire",
   "mana": 3,
   "id": 1476,
   "name": "Valknir Cavalry",
   "mana": 3,
   "id": 1477,
   "name": "Smith's Hammer",
   "mana": 5,
   "id": 1478,
   "name": "Tenderizer",
   "mana": 7,
   "id": 1479,
   "name": "Echoing Fury",
   "mana": 1,
   "id": 1480,
   "name": "Battle Artisan",
   "mana": 3,
   "id": 1481,
   "name": "Ravenous Chimera",
   "mana": 5,
   "id": 1482,
   "name": "Chieftain of Impulse",
   "mana": 7,
   "id": 167,
   "name": "Sulphuric Rain",
   "mana": 1,
   "id": 168,
   "name": "Lost In The Depths",
   "mana": 1,
   "id": 169,
   "name": "Horus, The Protector",
   "mana": 7,
   "id": 170,
   "name": "Blind Cyclops",
   "mana": 7,
   "id": 1483,
   "name": "Einar, the Frozen King",
   "mana": 6,
   "id": 1484,
   "name": "Valka's Captain",
   "mana": 2,
   "id": 173,
   "name": "Blade Trial Valkyrie",
   "mana": 6,
   "id": 175,
   "name": "Endow Wings",
   "mana": 4,
   "id": 1201,
   "name": "Shield Maiden",
   "mana": 2,
   "id": 1471,
   "name": "General Orythia",
   "mana": 7,
   "id": 1485,
   "name": "Oddi, Valka’s Herald",
   "mana": 3,
   "id": 1486,
   "name": "Anagreos, Daemon Prince",
   "mana": 9,
   "id": 222,
   "name": "Bast's Claws",
   "mana": 6,
   "id": 223,
   "name": "Tithe Collector",
   "mana": 2,
   "id": 226,
   "name": "Conniving Djinn",
   "mana": 2,
   "id": 229,
   "name": "Phalanx Champion",
   "mana": 4,
   "id": 1093,
   "name": "Svart Basilisk",
   "mana": 4,
   "id": 1094,
   "name": "Viking Outrider",
   "mana": 3,
   "id": 1207,
   "name": "Dionysian Drunk",
   "mana": 3,
   "id": 1487,
   "name": "Grand Hall",
   "mana": 4,
   "id": 230,
   "name": "Canopic Hoarder",
   "mana": 5,
   "id": 1104,
   "name": "Catapult",
   "mana": 5,
   "id": 1105,
   "name": "Amazon Flanker",
   "mana": 6,
   "id": 1106,
   "name": "Cyclops Marksman",
   "mana": 6,
   "id": 1108,
   "name": "Ladon, Uclid Dragon",
   "mana": 8,
   "id": 1109,
   "name": "Porphyrion, Dread Cyclops",
   "mana": 7,
   "id": 1488,
   "name": "Enraging Talisman",
   "mana": 4,
   "id": 1083,
   "name": "Planetar Centurion",
   "mana": 7,
   "id": 1202,
   "name": "Raving Necromancer",
   "mana": 2,
   "id": 1203,
   "name": "Highland Defender",
   "mana": 4,
   "id": 1204,
   "name": "Ballista",
   "mana": 3,
   "id": 1205,
   "name": "Hoplite",
   "mana": 2,
   "id": 1489,
   "name": "Archangel Bruiser",
   "mana": 4,
   "id": 1490,
   "name": "Sound the Charge",
   "mana": 3,
   "id": 1084,
   "name": "Skeleton Heavy",
   "mana": 2,
   "id": 1085,
   "name": "Phase Touched Golem",
   "mana": 3,
   "id": 1087,
   "name": "Burnished Bull",
   "mana": 7,
   "id": 1091,
   "name": "Blackguard",
   "mana": 8,
   "id": 1092,
   "name": "Vanir Lion",
   "mana": 4,
   "id": 1206,
   "name": "Viking Warmaiden",
   "mana": 2,
   "id": 1491,
   "name": "Rolling Thunder",
   "mana": 6,
   "id": 1492,
   "name": "Sole Survivor",
   "mana": 7,
   "id": 1493,
   "name": "Tartessian Minotaur",
   "mana": 5,
   "id": 101300,
   "name": "Explosive Barrel",
   "mana": 1,
   "id": 101301,
   "name": "Zombie",
   "mana": 1,
   "id": 101302,
   "name": "Shimmerscales",
   "mana": 5,
   "id": 101303,
   "name": "Final Draft",
   "mana": 1,
   "id": 210,
   "name": "Fallen Aether",
   "mana": 3,
   "id": 211,
   "name": "Deathsworn Raider",
   "mana": 3,
   "id": 213,
   "name": "Prodigious Armourer",
   "mana": 3,
   "id": 214,
   "name": "Shrine of Sothek",
   "mana": 3,
   "id": 215,
   "name": "Millenium Matryoshka",
   "mana": 4,
   "id": 221,
   "name": "Sit Down",
   "mana": 1,
   "id": 101304,
   "name": "Vibrant Fruit",
   "mana": 1,
   "id": 101306,
   "name": "Pallas’ Genius",
   "mana": 2,
   "id": 101307,
   "name": "Valka’s Presence",
   "mana": 2,
   "id": 1245,
   "name": "Crystal Rain",
   "mana": 5,
   "id": 1232,
   "name": "Beastfury Shaman",
   "mana": 3,
   "id": 1234,
   "name": "Born Again",
   "mana": 6,
   "id": 1235,
   "name": "Feral Shapeshifter",
   "mana": 5,
   "id": 1217,
   "name": "Wetlands Ogre",
   "mana": 4,
   "id": 1221,
   "name": "Ranger Firstbow",
   "mana": 2,
   "id": 1222,
   "name": "Assassin's Aim",
   "mana": 2,
   "id": 1223,
   "name": "Cutthroat Insight",
   "mana": 5,
   "id": 1238,
   "name": "Reconnaissance",
   "mana": 2,
   "id": 1239,
   "name": "Morgana's Grimoire",
   "mana": 2,
   "id": 1218,
   "name": "Eager Nobleborn",
   "mana": 2,
   "id": 1241,
   "name": "Tome Golem",
   "mana": 8,
   "id": 1246,
   "name": "Sip of Elixir",
   "mana": 2,
   "id": 1247,
   "name": "Seeing Stone",
   "mana": 1,
   "id": 1249,
   "name": "Wyrmbreath",
   "mana": 4,
   "id": 1211,
   "name": "Mire Bloodworm",
   "mana": 3,
   "id": 1212,
   "name": "Thanakris Spell-Locusts",
   "mana": 3,
   "id": 1213,
   "name": "Harp Cupid",
   "mana": 6,
   "id": 1219,
   "name": "Tough Townsfolk",
   "mana": 1,
   "id": 1220,
   "name": "Ambitious Adventurer",
   "mana": 2,
   "id": 1224,
   "name": "Uncanny Rogue",
   "mana": 4,
   "id": 1225,
   "name": "Fleshbind",
   "mana": 1,
   "id": 1226,
   "name": "Aether Vanguard",
   "mana": 6,
   "id": 1227,
   "name": "Veteran Cataphract",
   "mana": 7,
   "id": 1228,
   "name": "Shadow Paladin",
   "mana": 3,
   "id": 1229,
   "name": "Void Banshee",
   "mana": 2,
   "id": 1231,
   "name": "Thebian Brawler",
   "mana": 4,
   "id": 1242,
   "name": "Thaumnetic Golem",
   "mana": 6,
   "id": 1243,
   "name": "Tracking Bolt",
   "mana": 2,
   "id": 1244,
   "name": "Manathirst Golem",
   "mana": 5,
   "id": 101308,
   "name": "Orfeo’s Distraction",
   "mana": 2,
   "id": 101309,
   "name": "Neferu’s Sacrifice",
   "mana": 2,
   "id": 101310,
   "name": "Lysander’s Honor",
   "mana": 2,
   "id": 101311,
   "name": "Selena’s Lead",
   "mana": 2,
   "id": 101384,
   "name": "Final Draft v2",
   "mana": 1,
   "id": 101385,
   "name": "Final Draft v3",
   "mana": 1,
   "id": 1214,
   "name": "Bronze Servant",
   "mana": 3,
   "id": 101386,
   "name": "Final Draft v4",
   "mana": 1,
   "id": 1215,
   "name": "Ghost Marauder",
   "mana": 1,
   "id": 1216,
   "name": "Town Guardian",
   "mana": 4,
   "id": 101387,
   "name": "Final Draft v5",
   "mana": 1,
   "id": 101389,
   "name": "Oakspear Guard",
   "mana": 1,
   "id": 1256,
   "name": "Pack Stalk",
   "mana": 1,
   "id": 100119,
   "name": "Flip",
   "mana": 2,
   "id": 100121,
   "name": "Animal Bond",
   "mana": 2,
   "id": 100123,
   "name": "Slayer",
   "mana": 2,
   "id": 100126,
   "name": "Clear Mind",
   "mana": 2,
   "id": 1257,
   "name": "Pyreshell Beetle",
   "mana": 1,
   "id": 1258,
   "name": "Harvest Arachne",
   "mana": 3,
   "id": 100066,
   "name": "Warrior",
   "mana": 2,
   "id": 100067,
   "name": "Giant Elk",
   "mana": 2,
   "id": 100068,
   "name": "Tetria, Young Manaborn",
   "mana": 1,
   "id": 100070,
   "name": "Octavia, Manashard Queen",
   "mana": 1,
   "id": 100107,
   "name": "Undying Wish",
   "mana": 2,
   "id": 100108,
   "name": "Blood Ritual",
   "mana": 2,
   "id": 100111,
   "name": "Flourish",
   "mana": 2,
   "id": 100114,
   "name": "Onslaught",
   "mana": 2,
   "id": 100115,
   "name": "Summon Acolyte",
   "mana": 3,
   "id": 100117,
   "name": "Heal",
   "mana": 2,
   "id": 100144,
   "name": "Acolyte",
   "mana": 1,
   "id": 100145,
   "name": "Eagle",
   "mana": 0,
   "id": 100146,
   "name": "Panther",
   "mana": 1,
   "id": 100147,
   "name": "Crocodile",
   "mana": 3,
   "id": 100148,
   "name": "Badger",
   "mana": 0,
   "id": 100149,
   "name": "Bear",
   "mana": 3,
   "id": 100150,
   "name": "Reanimated Ghoul",
   "mana": 1,
   "id": 100151,
   "name": "Reanimated Corpse",
   "mana": 2,
   "id": 100153,
   "name": "Tough Malfunctioning Artifice",
   "mana": 1,
'''.split("\n")
logFile = ""
configFile = "config.txt"
text_size = 14
text_font = "Helvetica"
opacity = 1
warnedAboutLogFile = False

#These are generated cards that when drawn have a 0% chance of actually coming from your deck.
#Stuff like deutaria cards should be removed from this list if you can figure out how to shuffle them in to begin with
ignoredCards = ["Tetria, Young Manaborn", "Heptaria, Manashard Fiend", "Octavia, Manashard Queen", "Oakspear Guard"]



###############################-Backend Function Definitions-###############################
def createConfigFile():
    if (os.path.exists(configFile)):
        return

    log_path = "C:\\Users\\" + getpass.getuser() + "\\AppData\\LocalLow\\FuelGames"

    # taken from https://stackoverflow.com/questions/2014554/find-the-newest-folder-in-a-directory-in-python
    sub_dirs = [(log_path + "\\" + d) for d in os.listdir(log_path) if os.path.isdir((log_path + "\\" + d))]
    lastSubDir = max(sub_dirs, key=os.path.getmtime)

    default_log_file_path = lastSubDir + "\\output_log.txt"
    #print(default_log_file_path)

    conf = open(configFile, "w", encoding="utf8")
    conf.write("active_deck::==\n")
    conf.write("text_size::==14\n")
    conf.write("text_font::==Helvetica\n")
    conf.write("opacity::==1\n")
    conf.write("log_file_path::==" + default_log_file_path + "\n")
    #Add more lines as needed

    conf.close()

#This should be path to the folder above the folder where the log file is stored in. I.e. ...\FuelGames
def updateLogPath(log_path):
    global logFile
    if (log_path == ""):
        return

    conf = open(configFile, "r", encoding="utf8")
    lines = conf.readlines()
    conf.close()

    #taken from https://stackoverflow.com/questions/2014554/find-the-newest-folder-in-a-directory-in-python
    sub_dirs = [(log_path + "\\" + d) for d in os.listdir(log_path) if os.path.isdir((log_path + "\\" + d))]
    lastSubDir = max(sub_dirs, key=os.path.getmtime)

    logFile = lastSubDir + "\\output_log.txt"
    lines[4] = "log_file_path::==" + logFile + "\n"

    conf = open(configFile, "w", encoding="utf8")
    conf.writelines(lines)
    conf.close()

def updateFont(font="Helvetica"):
    global configFile
    global text_font

    text_font = font
    
    conf = open(configFile, "r", encoding="utf8")
    lines = conf.readlines()
    conf.close()

    

    lines[2] = "text_font::==" + font + "\n"

    conf = open(configFile, "w", encoding="utf8")
    conf.writelines(lines)
    conf.close()

    
def updateTextSize(val=0):
    global configFile
    global text_size
    conf = open(configFile, "r", encoding="utf8")
    lines = conf.readlines()
    conf.close()

    if (val > 0):
        text_size = val

    else:
        text_size = int(lines[1].split("::==")[1])

    lines[1] = "text_size::==" + str(text_size) + "\n"

    conf = open(configFile, "w", encoding="utf8")
    conf.writelines(lines)
    conf.close()



def updateOpacity(val):
    global configFile
    global opacity

    val = float(val)
    
    conf = open(configFile, "r", encoding="utf8")
    lines = conf.readlines()
    conf.close()

    if (val >= 0.1  and val <= 1):
        opacity = val
    else:
        opacity = 1

    lines[3] = "opacity::==" + str(opacity) + "\n"

    conf = open(configFile, "w", encoding="utf8")
    conf.writelines(lines)
    conf.close()

def getLogPath():
    conf = open(configFile, "r", encoding="utf8")
    lines = conf.readlines()
    conf.close()

    return lines[4].split("::==")[1].strip()


def getUrl(configFile):
    readFile = open(configFile, "r", encoding="utf8")
    lines = readFile.readlines()
    readFile.close()
    return lines[0].split("::==")[1]


def deckUrlToIdList(url):

    if (url == ""):
        return ""
    #IDs are seperated by commas in gudecks.com deck URLs
    urlSplit = url.split(",")

    #Before the first comma is garbage
    urlSplit.pop(0)

    #After the last comma is the final card ID, followed by a '?', follwed by garbage. Replace the last slot with just the number.
    if (len(urlSplit) < 30):
        return ""
    urlSplit[29] = urlSplit[29].split("?")[0]

    return urlSplit
        


def getDeckList(url):

    global allCards

    #get the IDs
    deckIDs = deckUrlToIdList(url)

    #Get the name and mana cost for each card based on their id.


    
    retList = []

    #Whether or not we need to look at the lines that say "name" and "mana"
    onFlag = False

    #Number of cards to add to deck
    numCards = 0

    #Storage string for the card name between iterations
    currName = ""

    
    for line in allCards:
        if ('"id"' in line):
            onFlag = False
            numCards = 1
            idStr = line.split(": ")[1].split(",")[0]
            if idStr in deckIDs:
                onFlag = True
                numCards = deckIDs.count(idStr)

        #If we have been signaled that this card is in the deck
        elif (onFlag):
            if ('"name"' in line):
                currName = line.split('": "')[1].split('"')[0]
            else:
                mana = line.split(": ")[1].split(",")[0]
                retList.append((currName, mana, numCards))
                


    #sort the list based first on mana cost, then alphabetically
    return sorted(retList, key = lambda element : (element[1], element[0]))


def getOpponentWebpage(logFileName):

    if (not os.path.exists(logFileName)):
        return -2

    inFile = open(logFileName, "r", encoding="utf8")



    guDecksPlayerPageBase = "https://gudecks.com/meta/player-stats?userId="

    for line in inFile:
        if (" o:PlayerInfo(apolloId" in line):
            opponentId = line.split(" o:PlayerInfo(apolloId: ")[1].split(",")[0]
            webbrowser.open((guDecksPlayerPageBase + opponentId), new=2, autoraise=True)
            inFile.close()
            return 1
        
    
    inFile.close()
    return -1

def getManaCost(name, allCards):

    retNext = False
    for line in allCards:
        if retNext:
            return line.split('"mana": ')[1].split(",")[0]
        if (name in line):
            retNext = True

    return 999

#deckList should equal the starting decklist of 30 cards
def updateDeckList(logFile, deckList, allCards):

    global ignoredCards

    #True if player turn, False if opponent turn
    currentTurn = False
    startTurnStr = '"action": "started"'
    endTurnStr = "Clicked End Turn"

    if (not os.path.exists(logFile)):
        return -2
    #There are a number of hard-coded exceptions because the logs are shit. I'm happy I could even figure out this in the first place
    logFileLines = open(logFile, "r", encoding="utf8")


    #Jason is a bitch
    jasonActive = False
    jasonStartText = "[WaitForDelve.Execute:115] - Delay Delve: CLIENT-Local-Human '<color=#00FF00>Jason, Medea's Muse</color>'"
    jasonCardToAdd = "Oops"
    jasonCardView = "TooltipHover: Init(), CardView: '"
    jasonDelve = "[DelveOverlay.Close:716] - DelveOverlay.Close"


    #Deception is even more of a bitch (this isn't close to finished implementing)
    removedFromBoardStr = "[BoardCreature.OnDisable:408]"
    currentWaitLines = 0
    maxWaitLines = 30 #This maybe could be 30


    #Sanctum
    attemptingToBuyStr = "[EventSolver.AttemptExecuteSanctumPurchase:1397]"
    successStr = "and was successful!"
    ignoreNextDraw = False #If you buy a card from the sanctum, you don't draw it


    #Generated Cards
    #This represents a card being move to hand from somewhere other than deck (if it's from deck, this line doesn't appear)
    moveCardStr = "MoveCardToZone -> "
    genCardStr = " to: Hand from:"


    #Normal stuff
    drawCardStr = "HandCard Init "
    
    for line in logFileLines:
        line = line.strip()
        #This is for deception bullshit
        currentWaitLines += 1

# <JASON>

        #Jason is a bitch and this code is jank
        if (jasonStartText in line):
            jasonActive = True
            continue

        #Note that this can get overwritten multiple times before becoming final, which is good.
        #This updates after a player hovers over a card, but only the final time before delve completion will be added
        elif (jasonActive and (jasonCardView in line)):
            jasonCardToAdd = line.split(jasonCardView)[1][:-1]
        
        elif (jasonActive and (jasonDelve in line)):

            #This message shows up twice, once for seemingly no reason, and the other right after you selected your card.
            #If there has been no card selected yet, then just wait.
            if (jasonCardToAdd == "Oops"):
                continue
            else:
                #We're adding a card to the deck. If it's already a card in our deck, we increase its value by 1. Otherwise, add a new card.
                found = False
                for card in deckList:
                    if (card[0] == jasonCardToAdd):
                        tempCard = (card[0], card[1], card[2] + 1)
                        deckList.remove(card)
                        deckList.append(tempCard)
                        found = True
                        break
                if (not found):
                    mana = getManaCost(jasonCardToAdd, allCards)
                    cardToAdd = (jasonCardToAdd, mana, 1)
                    deckList.append(cardToAdd)


                jasonCardToAdd = "Oops"
                jasonActive = False
                    

# </JASON>

# <DECEPTION>

        elif ((drawCardStr in line) and (currentWaitLines < maxWaitLines)):
            currentWaitLines = 0
            #print("Avoided a card")
            #This means we should ignore the draw because it came from
            continue

        elif (removedFromBoardStr in line):
            currentWaitLines = 0
# </DECEPTION>


# <SANCTUM>


        elif (currentTurn and (attemptingToBuyStr in line) and (successStr in line)):
            ignoreNextDraw = True


# </SANCTUM>

# <Generated cards>

        #Add generated cards to our deck so that when we "draw" them, there's effectively no change.
        elif(genCardStr in line):
            genCardToAdd = line.split(moveCardStr)[1].split(genCardStr)[0].strip()
            mana = getManaCost(genCardToAdd, allCards)
            found = False
            for card in deckList:
                if (card[0] == genCardToAdd):
                    found = True
                    tempCard = (card[0], card[1], card[2]+1)
                    deckList.remove(card)
                    deckList.append(tempCard)
            if (not found):
                tempCard = (genCardToAdd, mana, 1)
                deckList.append(tempCard)



# </Generated Cards>

# <Normal Cards Drawn>
        elif (drawCardStr in line):
            if (ignoreNextDraw):
                #We have a sanctum card
                ignoreNextDraw = False
                continue

            
            drawnCard = line.split(drawCardStr)[1]

            if (drawnCard in ignoredCards):
                #This shouldn't be in the deck
                continue
            found = False
            for card in deckList:
                if (str(card[0]).strip() == str(drawnCard).strip()):
                    #print(deckList)
                    #print("Removing: " + drawnCard)
                    found = True
                    if (card[2] == 1):
                        deckList.remove(card)
                    else:
                        tempCard = (card[0], card[1], card[2] - 1)
                        deckList.remove(card)
                        deckList.append(tempCard)
                        #print(tempCard)
                    break
            if (not found):
                mana = getManaCost(drawnCard, allCards)
                deckList.append((drawnCard, mana, -1))
# </Normal Cards Drawn>

# <Check Turn>
        elif(endTurnStr in line):
            currentTurn = False

        elif(startTurnStr in line):
            currentTurn = True
# </Check Turn>



    logFileLines.close()
    return sorted(deckList, key = lambda element : (element[1], element[0]))

###############################-Frontend Function Definitions-###############################

def opponentsWebpage():
    res = getOpponentWebpage(logFile)
    if (res == -1):
        alert = QMessageBox()
        alert.setText('Opponent User ID Not Found. Please try again in a few seconds.')
        alert.exec()
    elif(res == -2):
        alert = QMessageBox()
        alert.setText('No valid log file found. Please check path.')
        alert.exec()



def textFromDeckList(cardList=None):
    if (cardList == None):
        cardList = getDeckList(getUrl(configFile))
    
    retStr = ""

    first = True
    #card is represented by (name, mana, number of card)
    for card in cardList:

        #So we don't add a newline after the last line
        if (not first):
            retStr += "\n"
        else:
            first = False

        
        retStr += "[" + card[1] + "] " + card[0]
        if (not (card[2] == 1)):
            retStr += " (" + str(card[2]) + ")"
        

    return retStr





###############################-Window Classes-###############################

class MainWindow(QWidget):
    def __init__(self):
        super().__init__()

        global text_font
        global text_size

        self.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        self.tempWindow = None
        layout = QVBoxLayout()
        self.setWindowTitle("JMoney's Deck Tracker")

        
        self.opponentPageButton = QPushButton("Open Opponent's GUDecks Page", self)
        self.opponentPageButton.clicked.connect(opponentsWebpage)
        self.opponentPageButton.setFont(QFont(text_font, text_size))
        layout.addWidget(self.opponentPageButton)



        self.enterDeckCodeButton = QPushButton("Set Active Deck", self)
        self.enterDeckCodeButton.clicked.connect(self.inputDeckCode)
        self.enterDeckCodeButton.setFont(QFont(text_font, text_size))
        layout.addWidget(self.enterDeckCodeButton)

        self.settingsButton = QPushButton("Settings", self)
        self.settingsButton.clicked.connect(self.settings)
        self.settingsButton.setFont(QFont(text_font, text_size))
        layout.addWidget(self.settingsButton)


        self.deckTrackerLabel = QLabel()
        self.deckTrackerLabel.setFont(QFont(text_font, text_size))
        layout.addWidget(self.deckTrackerLabel)


        self.setLayout(layout)
        self.show()
        
        self.my_timer = QtCore.QTimer()
        self.my_timer.timeout.connect(self.update)
        self.my_timer.start(1000) #1 sec


    def update(self):
        #Constantly looping update to keep the deck tracker up to date
        global configFile #bleh, I know, but no good way around it
        global logFile
        global opacity
        global text_font
        global text_size
        global warnedAboutLogFile


        deck = updateDeckList(logFile, getDeckList(getUrl(configFile)), allCards)
        if (deck == -2):
            if (not warnedAboutLogFile):
                alert = QMessageBox()
                alert.setText('No valid log file found. Please check path.')
                alert.exec()
                warnedAboutLogFile = True

            self.deckTrackerLabel.setText("No Log File Found")
        else:
            self.deckTrackerLabel.setText(textFromDeckList(deck))



        #change fonts
        self.opponentPageButton.setFont(QFont(text_font, text_size))
        self.enterDeckCodeButton.setFont(QFont(text_font, text_size))
        self.settingsButton.setFont(QFont(text_font, text_size))
        self.deckTrackerLabel.setFont(QFont(text_font, text_size))


        #change opacity
        self.setWindowOpacity(opacity)
        


    def inputDeckCode(self):
        self.tempWindow = ActiveDeckWindow()

    def settings(self):
        self.tempWindow = SettingsWindow()


class ActiveDeckWindow(QWidget):
    def __init__(self):   
        super().__init__()

        global text_size
        global text_font
        global opacity


        self.setWindowOpacity(opacity)
        self.setWindowTitle("JMoney's Deck Tracker")
        self.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        layout = QVBoxLayout()
        self.urlLabel = QLabel("Enter the URL to your deck here:")
        self.urlLabel.setFont(QFont(text_font, text_size))
        layout.addWidget(self.urlLabel)

        self.deckLineEdit = QLineEdit("")
        self.deckLineEdit.setFont(QFont(text_font, text_size))
        layout.addWidget(self.deckLineEdit)

        self.confirmButton = QPushButton("Confirm", self)
        self.confirmButton.clicked.connect(self.confirmCode)
        self.confirmButton.setFont(QFont(text_font, text_size))
        layout.addWidget(self.confirmButton)

        self.cancelButton = QPushButton("Cancel", self)
        self.cancelButton.clicked.connect(self.cancel)
        self.cancelButton.setFont(QFont(text_font, text_size))
        layout.addWidget(self.cancelButton)

        self.setLayout(layout)
        self.show()


    def confirmCode(self):
        global configFile #bleh, I know, but no good way around it
        deckUrl = self.deckLineEdit.text()

        readFile = open(configFile, "r", encoding="utf8")
        lines = readFile.readlines()
        readFile.close()
        lines[0] = "active_deck::==" + deckUrl + "\n"

        writeFile = open(configFile, "w", encoding="utf8")
        writeFile.writelines(lines)
        writeFile.close()
        self.close()

    def cancel(self):
        self.close()



class SettingsWindow(QWidget):
    def __init__(self):
        super().__init__()

        global text_size
        global text_font
        global opacity

        self.setWindowOpacity(opacity)
        self.setWindowTitle("JMoney's Deck Tracker")
        self.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        layout = QVBoxLayout()


        self.textSizeLabel = QLabel("Enter desired text size (Currently " + str(text_size) + "):")
        self.textSizeLabel.setFont(QFont(text_font, text_size))
        layout.addWidget(self.textSizeLabel)

        self.textSizeEdit = QLineEdit("")
        self.textSizeEdit.setFont(QFont(text_font, text_size))
        layout.addWidget(self.textSizeEdit)
        

        self.textFontLabel = QLabel("Enter desired text font (Currently " + str(text_font) + "):")
        self.textFontLabel.setFont(QFont(text_font, text_size))
        layout.addWidget(self.textFontLabel)

        self.textFontEdit = QLineEdit("")
        self.textFontEdit.setFont(QFont(text_font, text_size))
        layout.addWidget(self.textFontEdit)


        self.opacityLabel = QLabel("Enter desired opacity (Currently " + str(opacity) + "; Range 0.1-1):")
        self.opacityLabel.setFont(QFont(text_font, text_size))
        layout.addWidget(self.opacityLabel)

        self.opacityEdit = QLineEdit("")
        self.opacityEdit.setFont(QFont(text_font, text_size))
        layout.addWidget(self.opacityEdit)


        self.pathLabel = QLabel("Enter path to 'FuelGames' log folder:")
        self.pathLabel.setFont(QFont(text_font, text_size))
        layout.addWidget(self.pathLabel)

        self.pathEdit = QLineEdit("")
        self.pathEdit.setFont(QFont(text_font, text_size))
        layout.addWidget(self.pathEdit)


        self.confirmButton = QPushButton("Apply", self)
        self.confirmButton.clicked.connect(self.confirm)
        self.confirmButton.setFont(QFont(text_font, text_size))
        layout.addWidget(self.confirmButton)

        self.cancelButton = QPushButton("Cancel", self)
        self.cancelButton.clicked.connect(self.cancel)
        self.cancelButton.setFont(QFont(text_font, text_size))
        layout.addWidget(self.cancelButton)

        self.setLayout(layout)
        self.show()


    def confirm(self):
        global text_size
        global text_font
        global opacity
        global warnedAboutLogFile

        if (not str(self.textSizeEdit.text()) == ""):
            text_size = int(self.textSizeEdit.text())
            
            if (text_size < 5):
                text_size = 5
            elif (text_size > 80):
                text_size = 80
            
            updateTextSize(text_size)
     
        if (not str(self.textFontEdit.text()) == ""):
            text_font = self.textFontEdit.text()
            updateFont(text_font)

        if (not str(self.opacityEdit.text()) == ""):
            opacity = self.opacityEdit.text()
            updateOpacity(float(opacity))

        if (not str(self.pathEdit.text()) == ""):
            warnedAboutLogFile = False
            updateLogPath(self.pathEdit.text())

        self.close()

    def cancel(self):
        self.close()

        
###############################-Main-###############################



createConfigFile()
logFile = getLogPath()
app = QApplication([])
app.setStyle('Fusion')
mainWindow = MainWindow()

#This is stolen from: https://stackoverflow.com/questions/48256772/dark-theme-for-qt-widgets
palette = QPalette()
palette.setColor(QPalette.Window, QColor(53, 53, 53))
palette.setColor(QPalette.WindowText, Qt.white)
palette.setColor(QPalette.Base, QColor(25, 25, 25))
palette.setColor(QPalette.AlternateBase, QColor(53, 53, 53))
palette.setColor(QPalette.ToolTipBase, Qt.black)
palette.setColor(QPalette.ToolTipText, Qt.white)
palette.setColor(QPalette.Text, Qt.white)
palette.setColor(QPalette.Button, QColor(53, 53, 53))
palette.setColor(QPalette.ButtonText, Qt.white)
palette.setColor(QPalette.BrightText, Qt.red)
palette.setColor(QPalette.Link, QColor(42, 130, 218))
palette.setColor(QPalette.Highlight, QColor(42, 130, 218))
palette.setColor(QPalette.HighlightedText, Qt.black)
app.setPalette(palette)

app.exec()
